/*
 * Englisch Klasse 6 - Klausurvorbereitung (Theme 5: will/won't, Wetter,
 * Adverbien, Bahnhof, E-Mail). Aufgaben aus ChatGPT-Analyse, von Claude
 * auf App-Schema geprueft/korrigiert. Eigene Aufgaben, keine Buchkopien.
 *
 * Typen: "mc" | "text" (eindeutige Antwort, Gross/Klein egal) |
 *        "freitext" (freie Antwort -> KI gibt Feedback, kein richtig/falsch)
 */
window.SCHULWEG = window.SCHULWEG || { faecher: {} };

window.SCHULWEG.faecher["englisch-6"] = {
  fach: "Englisch",
  klasse: 6,
  farbe: "englisch",
  icon: "🇬🇧",
  themen: [
    {
      id: "klausur-theme5",
      titel: "Klausurvorbereitung (Theme 5)",
      seiten: "S.94–96, 106–107, 157",
      voraussetzung: "einfache Zukunftssätze mit 'I'll' und den wichtigsten Wortschatz",
      intro:
        "Diese Übungen sind genau auf deine Klassenarbeit zugeschnitten: will/won't, Wetter, Adverbien, Bahnhof und das E-Mail-Schreiben. Sie werden langsam schwerer.",
      aufgaben: [
        {
          typ: "mc",
          frage: "Tomorrow it ____ rain.",
          antworten: ["will", "won't", "is"],
          richtig: "will",
          erklaerung: "Für Vorhersagen in der Zukunft nutzt du 'will'.",
          schritte: ["Achte auf 'Tomorrow' → Zukunft.", "Nutze 'will'."],
          fehler: {
            "won't": "'won't' heißt, dass etwas NICHT passiert. Hier ist eine normale Vorhersage gemeint → will.",
            "is": "'is' ist Gegenwart. Für morgen brauchst du die Zukunft mit 'will'."
          }
        },
        {
          typ: "text",
          frage: "Complete: I think it ___ (be) sunny tomorrow.",
          richtig: "will be",
          erklaerung: "Nach 'I think' und für morgen nutzt du will + Grundform: 'will be'.",
          schritte: ["Denke an die Zukunft (tomorrow).", "Setze 'will be' ein."],
          fehler: {
            "is": "Das ist Gegenwart. Für morgen brauchst du 'will be'.",
            "be": "'be' allein reicht nicht – es fehlt 'will'.",
            "will": "Es fehlt das 'be': richtig ist 'will be'."
          }
        },
        {
          typ: "mc",
          frage: "Choose the correct word: She runs ____.",
          antworten: ["quick", "quickly", "careful"],
          richtig: "quickly",
          erklaerung: "Wie jemand etwas tut, beschreibt ein Adverb (oft mit -ly).",
          schritte: ["Suche das Verb: runs.", "Beschreibe das Verb mit einem Adverb: quickly."],
          fehler: {
            "quick": "'quick' ist ein Adjektiv. Für das Verb brauchst du das Adverb 'quickly'.",
            "careful": "Passt inhaltlich nicht – und ist außerdem ein Adjektiv."
          }
        },
        {
          typ: "text",
          frage: "Complete: He is very ___ (careful / carefully) with his work.",
          richtig: "careful",
          erklaerung: "Nach 'is' (Form von to be) steht ein Adjektiv.",
          schritte: ["Erkenne to be: 'is'.", "Nach to be nutzt du ein Adjektiv: careful."],
          fehler: {
            "carefully": "Nach 'is' braucht man ein Adjektiv, kein Adverb – also 'careful'."
          }
        },
        {
          typ: "mc",
          frage: "Which word belongs to the train station?",
          antworten: ["platform", "snow", "tent"],
          richtig: "platform",
          erklaerung: "'platform' (Bahnsteig) gehört zum Bahnhof.",
          schritte: ["Denke an den Bahnhof.", "Wähle das passende Wort."],
          fehler: {
            "snow": "'snow' (Schnee) gehört zum Wetter.",
            "tent": "'tent' (Zelt) gehört zum Camping."
          }
        },
        {
          typ: "text",
          frage: "Complete: The train ___ (leave) from Platform 4 at 9 a.m.",
          richtig: "leaves",
          erklaerung: "Feste Fahrpläne stehen im Simple Present – bei 'the train' (it) mit -s.",
          schritte: ["Es geht um einen Fahrplan → Simple Present.", "Bei 'the train' (it) kommt ein -s dran: leaves."],
          fehler: {
            "leave": "Bei 'the train' (it) fehlt das -s: richtig ist 'leaves'.",
            "will leave": "Bei einem festen Fahrplan nimmt man das Simple Present: 'leaves'."
          }
        },
        {
          typ: "mc",
          frage: "It's minus five degrees. It's ____.",
          antworten: ["windy", "freezing", "sunny"],
          richtig: "freezing",
          erklaerung: "Bei Minusgraden ist es eiskalt: freezing.",
          schritte: ["Lies die Temperatur: minus five.", "Wähle das Wort für eiskalt: freezing."],
          fehler: {
            "windy": "'windy' (windig) sagt nichts über die Temperatur.",
            "sunny": "'sunny' (sonnig) passt nicht zu minus fünf Grad."
          }
        },
        {
          typ: "text",
          frage: "Complete: I hope it ___ rain tomorrow.",
          richtig: "won't",
          akzeptiert: ["will not"],
          erklaerung: "Wenn du hoffst, dass etwas NICHT passiert, nutzt du 'won't' (= will not).",
          schritte: ["Achte auf 'I hope' – du wünschst dir etwas.", "Du willst KEINEN Regen → won't."],
          fehler: {
            "will": "'will' würde heißen, dass es regnet – das Gegenteil von dem, was man hofft.",
            "will not": "Richtig gedacht! Schreib nur die Kurzform: won't.",
            "doesn't": "Es geht um morgen (Zukunft): nutze 'won't'."
          }
        },
        {
          typ: "mc",
          frage: "Look at the dark clouds! It ____ rain soon.",
          antworten: ["will", "won't", "does"],
          richtig: "will",
          erklaerung: "Anzeichen wie dunkle Wolken → Vorhersage mit will.",
          schritte: ["Dunkle Wolken = Anzeichen für Regen.", "Vorhersage mit 'will'."],
          fehler: {
            "won't": "Dunkle Wolken heißt: Es WIRD regnen. 'won't' wäre das Gegenteil.",
            "does": "'does' passt hier nicht – für eine Vorhersage nutzt du 'will'."
          }
        },
        {
          typ: "text",
          frage: "Make it negative: 'It will snow.' → 'It ___ snow.'",
          richtig: "won't",
          akzeptiert: ["will not"],
          erklaerung: "Die Verneinung von 'will' ist 'won't' (= will not).",
          schritte: ["will + not = won't.", "'It won't snow.'"],
          fehler: {
            "will": "Du sollst den Satz VERNEINEN: won't.",
            "doesn't": "Die Verneinung der Zukunft ist won't, nicht doesn't."
          }
        },
        {
          typ: "text",
          frage: "Adverb of 'slow' = ___",
          richtig: "slowly",
          erklaerung: "Aus dem Adjektiv 'slow' wird mit -ly das Adverb 'slowly'.",
          schritte: ["Adjektiv: slow.", "+ -ly = slowly."],
          fehler: {
            "slow": "Das ist das Adjektiv. Das Adverb ist slowly.",
            "slowley": "Fast! Die richtige Schreibweise ist slowly."
          }
        },
        {
          typ: "mc",
          frage: "He speaks very ____.",
          antworten: ["quiet", "quietly", "quietness"],
          richtig: "quietly",
          erklaerung: "Wie er spricht (Verb) → Adverb: quietly.",
          schritte: ["Verb: speaks.", "Beschreibe es mit einem Adverb: quietly."],
          fehler: {
            "quiet": "'quiet' ist ein Adjektiv. Das Verb 'speaks' braucht ein Adverb: quietly.",
            "quietness": "Das ist ein Nomen (die Stille)."
          }
        },
        {
          typ: "text",
          frage: "Complete: She is a ___ (careful / carefully) driver.",
          richtig: "careful",
          erklaerung: "Vor einem Nomen ('driver') steht ein Adjektiv.",
          schritte: ["'driver' ist ein Nomen.", "Davor steht ein Adjektiv: careful."],
          fehler: {
            "carefully": "Vor dem Nomen 'driver' steht ein Adjektiv: careful (nicht das Adverb)."
          }
        },
        {
          typ: "mc",
          frage: "She sings ____.",
          antworten: ["beautiful", "beautifully"],
          richtig: "beautifully",
          erklaerung: "Wie sie singt (Verb) → Adverb: beautifully.",
          schritte: ["Verb: sings.", "Adverb dazu: beautifully."],
          fehler: {
            "beautiful": "'beautiful' ist ein Adjektiv. Das Verb 'sings' braucht ein Adverb: beautifully."
          }
        },
        {
          typ: "mc",
          frage: "There is a lot of wind today. It's ____.",
          antworten: ["foggy", "windy", "hot"],
          richtig: "windy",
          erklaerung: "Viel Wind → it's windy.",
          schritte: ["Wind = wind.", "windig = windy."],
          fehler: {
            "foggy": "'foggy' heißt neblig.",
            "hot": "'hot' heißt heiß – das passt nicht zu Wind."
          }
        },
        {
          typ: "mc",
          frage: "I can't see far. There is a lot of ____.",
          antworten: ["fog", "sun", "snow"],
          richtig: "fog",
          erklaerung: "Schlechte Sicht → Nebel (fog).",
          schritte: ["Man sieht schlecht.", "Das Wort dafür ist fog (Nebel)."],
          fehler: {
            "sun": "Bei Sonne sieht man gut.",
            "snow": "Schnee ist möglich, aber das Wort für schlechte Sicht ist fog."
          }
        },
        {
          typ: "text",
          frage: "Translate into English: 'bewölkt' = ___",
          richtig: "cloudy",
          erklaerung: "Wolke = cloud, bewölkt = cloudy.",
          schritte: ["Wolke = cloud.", "bewölkt = cloudy."],
          fehler: {
            "clody": "Fast! Die Schreibweise ist cloudy.",
            "windy": "'windy' heißt windig, nicht bewölkt."
          }
        },
        {
          typ: "mc",
          frage: "You need a ____ to travel by train.",
          antworten: ["ticket", "tent", "towel"],
          richtig: "ticket",
          erklaerung: "Zum Bahnfahren brauchst du eine Fahrkarte: ticket.",
          schritte: ["Denke an den Bahnhof.", "Fahrkarte = ticket."],
          fehler: {
            "tent": "'tent' (Zelt) gehört zum Camping.",
            "towel": "'towel' heißt Handtuch."
          }
        },
        {
          typ: "text",
          frage: "Opposite of 'to arrive' (at the station) = to ___",
          richtig: "leave",
          akzeptiert: ["depart"],
          erklaerung: "ankommen = arrive, abfahren = leave (oder depart).",
          schritte: ["arrive = ankommen.", "Das Gegenteil ist leave (abfahren)."],
          fehler: {
            "arrive": "Das ist dasselbe Wort – das Gegenteil ist leave.",
            "go": "Zu allgemein. Am Bahnhof sagt man leave (oder depart)."
          }
        },
        {
          typ: "freitext",
          frage: "Finish with your own idea: 'I'll take my rain gear because ___.' (Schreibe einen ganzen Grund.)",
          musterloesung: "I'll take my rain gear because it will rain.",
          tipp: "Am besten mit 'will', z. B. 'because it will rain'."
        },
        {
          typ: "freitext",
          frage: "Write one sentence about your weekend: 'On Saturday I'll ___.'",
          musterloesung: "On Saturday I'll play football with my friends.",
          tipp: "Beginne mit 'On Saturday I'll' und schreibe einen ganzen Satz."
        },
        {
          typ: "freitext",
          frage: "Write one sentence with a reason: 'I think I'll ___ because ___.'",
          musterloesung: "I think I'll stay at home because it will rain.",
          tipp: "Verbinde eine Zukunftsabsicht (I'll …) mit einem Grund (because …)."
        },
        {
          typ: "freitext",
          frage: "Mini-E-Mail (4 Sätze): Erzähle deiner Freundin/deinem Freund vom nächsten Wochenende. Benutze: I'll, won't, because und ein Wetterwort.",
          musterloesung: "Hi! Next weekend I'll go camping with my family. I hope it won't rain because we want to hike. It will be sunny, so I'll take my sunglasses. See you soon!",
          tipp: "Schreibe 4 ganze Sätze und benutze alle vier: I'll, won't, because und ein Wetterwort."
        },
        {
          typ: "freitext",
          frage: "Write a weather forecast for tomorrow (2 sentences). Use 'will' and at least one weather word.",
          musterloesung: "Tomorrow it will be cloudy in the morning. In the afternoon it will be sunny and warm.",
          tipp: "Nutze 'will' und mindestens ein Wetterwort (sunny, cloudy, windy …)."
        }
      ]
    },
    {
      id: "vokabeln-unit5",
      titel: "Vokabeln Unit 5",
      seiten: "S.213–214 (Vokabelliste)",
      voraussetzung: "nichts Besonderes – einfach die neuen Wörter üben",
      intro: "Trainiere die wichtigen Vokabeln aus Unit 5. Tippe das englische Wort – Groß-/Kleinschreibung ist egal.",
      aufgaben: [
        { typ: "text", frage: "Wetter: 'windig' auf Englisch?", richtig: "windy", erklaerung: "windig = windy.", schritte: ["der Wind = wind", "windig = windy"] },
        { typ: "text", frage: "Wetter: 'der Wind' auf Englisch?", richtig: "wind", erklaerung: "der Wind = wind.", schritte: ["wind = der Wind"] },
        { typ: "text", frage: "Wetter: 'wolkig' auf Englisch?", richtig: "cloudy", erklaerung: "wolkig = cloudy.", schritte: ["die Wolke = cloud", "wolkig = cloudy"] },
        { typ: "text", frage: "Wetter: 'die Wolke' auf Englisch?", richtig: "cloud", erklaerung: "die Wolke = cloud.", schritte: ["cloud = die Wolke"] },
        { typ: "text", frage: "Wetter: 'eiskalt / eisig' auf Englisch?", richtig: "freezing", erklaerung: "eiskalt = freezing.", schritte: ["freeze = (ein)frieren", "freezing = eiskalt"] },
        { typ: "text", frage: "Wetter: 'der Schnee' auf Englisch?", richtig: "snow", erklaerung: "der Schnee = snow.", schritte: ["snow = der Schnee"] },
        { typ: "text", frage: "Wetter: 'verschneit / schneebedeckt' auf Englisch?", richtig: "snowy", erklaerung: "verschneit = snowy.", schritte: ["snow = Schnee", "snowy = verschneit"] },
        { typ: "text", frage: "Wetter: 'kühl' auf Englisch?", richtig: "cool", erklaerung: "kühl = cool.", schritte: ["cool = kühl"] },
        { typ: "text", frage: "Wetter: 'der Grad' (Temperatur) auf Englisch?", richtig: "degree", akzeptiert: ["degrees"], erklaerung: "der Grad = degree (Mehrzahl: degrees).", schritte: ["14 degrees = 14 Grad"] },
        { typ: "text", frage: "Wetter: 'die Jahreszeit' auf Englisch?", richtig: "season", erklaerung: "die Jahreszeit = season.", schritte: ["four seasons = vier Jahreszeiten"] },
        { typ: "text", frage: "Jahreszeit: 'der Frühling' auf Englisch?", richtig: "spring", erklaerung: "der Frühling = spring.", schritte: ["spring = Frühling"] },
        { typ: "text", frage: "Jahreszeit: 'der Sommer' auf Englisch?", richtig: "summer", erklaerung: "der Sommer = summer.", schritte: ["summer = Sommer"] },
        { typ: "text", frage: "Jahreszeit: 'der Herbst' auf Englisch?", richtig: "autumn", akzeptiert: ["fall"], erklaerung: "der Herbst = autumn (in den USA: fall).", schritte: ["autumn = Herbst"] },
        { typ: "text", frage: "Jahreszeit: 'der Winter' auf Englisch?", richtig: "winter", erklaerung: "der Winter = winter.", schritte: ["winter = Winter"] },
        { typ: "mc", frage: "Was bedeutet 'autumn'?", antworten: ["Herbst", "Frühling", "Sommer"], richtig: "Herbst", erklaerung: "autumn = Herbst.", schritte: ["autumn = Herbst"], fehler: { "Frühling": "Frühling heißt spring.", "Sommer": "Sommer heißt summer." } },
        { typ: "mc", frage: "Welches Wort bedeutet 'eiskalt'?", antworten: ["freezing", "cool", "windy"], richtig: "freezing", erklaerung: "eiskalt = freezing.", schritte: ["freezing = eiskalt"], fehler: { "cool": "cool heißt kühl.", "windy": "windy heißt windig." } },
        { typ: "text", frage: "Allgemein: 'die Zukunft' auf Englisch?", richtig: "future", erklaerung: "die Zukunft = future.", schritte: ["future = Zukunft"] },
        { typ: "text", frage: "Allgemein: 'der Zug' auf Englisch?", richtig: "train", erklaerung: "der Zug = train.", schritte: ["train = Zug"] },
        { typ: "text", frage: "Allgemein: 'fotografieren / Fotos machen' auf Englisch?", richtig: "take photos", akzeptiert: ["take a photo", "take photo", "take a picture"], erklaerung: "Fotos machen = take photos (NICHT make photos).", schritte: ["take a photo = ein Foto machen"] },
        { typ: "text", frage: "Adverb: 'langsam' (wie man etwas tut) auf Englisch?", richtig: "slowly", erklaerung: "langsam (Adverb) = slowly.", schritte: ["slow = langsam (Adjektiv)", "slowly = langsam (Adverb)"] },
        { typ: "text", frage: "Adverb: 'schnell' (wie man etwas tut) auf Englisch?", richtig: "quickly", erklaerung: "schnell (Adverb) = quickly.", schritte: ["quick = schnell (Adjektiv)", "quickly = schnell (Adverb)"] },
        { typ: "text", frage: "Weg: 'geradeaus' auf Englisch?", richtig: "straight on", akzeptiert: ["straight ahead"], erklaerung: "geradeaus = straight on.", schritte: ["Go straight on. = Geh geradeaus."] },
        { typ: "mc", frage: "Wie sagst du 'Bieg links ab'?", antworten: ["Turn left.", "Turn right.", "Go straight on."], richtig: "Turn left.", erklaerung: "links abbiegen = turn left.", schritte: ["left = links"], fehler: { "Turn right.": "Das heißt rechts abbiegen.", "Go straight on.": "Das heißt geradeaus gehen." } },
        { typ: "text", frage: "Weg: 'vorwärts / nach vorn' auf Englisch?", richtig: "forward", erklaerung: "nach vorn = forward.", schritte: ["one step forward = ein Schritt nach vorn"] },
        { typ: "text", frage: "Wortschatz: 'die Sicherheit' auf Englisch?", richtig: "safety", erklaerung: "die Sicherheit = safety.", schritte: ["safe = sicher", "safety = Sicherheit"] },
        { typ: "text", frage: "Wortschatz: 'der Kompass' auf Englisch?", richtig: "compass", erklaerung: "der Kompass = compass.", schritte: ["compass = Kompass"] },
        { typ: "text", frage: "Wortschatz: 'der Abfall / Müll' auf Englisch?", richtig: "litter", erklaerung: "der Abfall = litter.", schritte: ["litter bin = Mülleimer"] },
        { typ: "text", frage: "Wortschatz: 'der Mülleimer' auf Englisch?", richtig: "litter bin", akzeptiert: ["bin"], erklaerung: "der Mülleimer = litter bin.", schritte: ["litter = Abfall", "litter bin = Mülleimer"] },
        { typ: "text", frage: "Wortschatz: 'die Brücke' auf Englisch?", richtig: "bridge", erklaerung: "die Brücke = bridge.", schritte: ["bridge = Brücke"] },
        { typ: "text", frage: "Wortschatz: 'der Stein' auf Englisch?", richtig: "stone", erklaerung: "der Stein = stone.", schritte: ["stone = Stein"] }
      ]
    },
    {
      id: "durchsagen",
      titel: "Bahnhof: Durchsagen verstehen",
      seiten: "S.100",
      voraussetzung: "Bahnhofswortschatz (platform, train, leave …)",
      intro: "Lies die Durchsage genau und beantworte die Frage. So übst du, das Wichtigste herauszuhören – hier zum Lesen.",
      aufgaben: [
        {
          typ: "text",
          frage: "Announcement: 'The train to London leaves from platform 3.' — From which platform does the train leave? (number)",
          richtig: "3",
          erklaerung: "platform = Gleis/Bahnsteig. Hier: platform 3.",
          schritte: ["Suche das Wort 'platform' in der Durchsage.", "Dahinter steht die Zahl: 3."]
        },
        {
          typ: "text",
          frage: "Announcement: 'The train to Manchester is delayed by 10 minutes.' — How many minutes is the delay? (number)",
          richtig: "10",
          erklaerung: "delayed = verspätet. 10 minutes = 10 Minuten.",
          schritte: ["'delayed' = Verspätung.", "Suche die Zahl der Minuten: 10."]
        },
        {
          typ: "mc",
          frage: "Announcement: 'The 8 o'clock train to Bristol has been cancelled.' — What happened to the train?",
          antworten: ["It is cancelled.", "It is delayed.", "It is on time."],
          richtig: "It is cancelled.",
          erklaerung: "cancelled = fällt aus / gestrichen.",
          schritte: ["Suchwort: cancelled.", "cancelled = fällt aus."],
          fehler: {
            "It is delayed.": "'delayed' wäre verspätet. Hier steht 'cancelled' = fällt aus.",
            "It is on time.": "'cancelled' heißt, der Zug fährt gar nicht."
          }
        },
        {
          typ: "mc",
          frage: "Announcement: 'The next train to York will leave from platform 5.' — Where does the train leave from?",
          antworten: ["Platform 3", "Platform 5", "Platform 15"],
          richtig: "Platform 5",
          erklaerung: "In der Durchsage steht 'platform 5'.",
          schritte: ["Suche 'platform'.", "platform 5."],
          fehler: {
            "Platform 3": "In der Durchsage steht platform 5, nicht 3.",
            "Platform 15": "Es ist platform 5, nicht 15."
          }
        },
        {
          typ: "mc",
          frage: "Announcement: 'The train from Edinburgh is now arriving at platform 2.' — What is happening?",
          antworten: ["A train is arriving.", "A train is leaving.", "A train is cancelled."],
          richtig: "A train is arriving.",
          erklaerung: "arriving = ankommend – der Zug kommt gerade an.",
          schritte: ["Suchwort: arriving.", "arrive = ankommen."],
          fehler: {
            "A train is leaving.": "Abfahren wäre 'leaving' / 'departing'. Hier: 'arriving' = ankommen.",
            "A train is cancelled.": "Ausfallen wäre 'cancelled'. Hier kommt der Zug an."
          }
        },
        {
          typ: "mc",
          frage: "Announcement: 'Please mind the gap between the train and the platform.' — What should you watch out for?",
          antworten: ["The gap between the train and the platform.", "Your ticket.", "The weather."],
          richtig: "The gap between the train and the platform.",
          erklaerung: "mind the gap = Achte auf den Spalt (zwischen Zug und Bahnsteig).",
          schritte: ["mind = achte auf.", "gap = Spalt/Lücke."],
          fehler: {
            "Your ticket.": "Von einem Ticket ist hier nicht die Rede.",
            "The weather.": "Es geht um den Spalt am Bahnsteig, nicht ums Wetter."
          }
        },
        {
          typ: "text",
          frage: "Announcement: 'The train to Leeds leaves at a quarter to four.' — What time does the train leave? (e.g. 6:15)",
          richtig: "3:45",
          akzeptiert: ["15:45", "quarter to four", "a quarter to four"],
          erklaerung: "a quarter to four = Viertel vor vier = 3:45 (oder 15:45).",
          schritte: ["quarter to = 15 Minuten vor der vollen Stunde.", "quarter to four = 3:45."]
        },
        {
          typ: "mc",
          frage: "Which word means the train comes LATER than planned?",
          antworten: ["delayed", "cancelled", "on time"],
          richtig: "delayed",
          erklaerung: "delayed = verspätet (kommt später).",
          schritte: ["delay = Verzögerung.", "delayed = verspätet."],
          fehler: {
            "cancelled": "'cancelled' heißt: der Zug fällt ganz aus.",
            "on time": "'on time' heißt pünktlich."
          }
        }
      ]
    },
    {
      id: "aufarbeitung",
      titel: "Aufarbeitung: deine Lernfelder",
      seiten: "gezielt aus deinen letzten Arbeiten",
      voraussetzung: "Grundwortschatz – wir schließen gezielt Lücken",
      intro: "Diese Übungen sind genau auf deine letzten Englischarbeiten zugeschnitten: Simple Past (auch unregelmäßige Verben), was/were und die Verneinung, und die richtigen Präpositionen. Keine Sorge – das kriegen wir Stück für Stück hin.",
      aufgaben: [
        { typ: "text", frage: "Past tense of 'find': Yesterday I ___ my keys.", richtig: "found", erklaerung: "'find' ist unregelmäßig: find → found.", schritte: ["find ist unregelmäßig.", "find → found."], fehler: { "finded": "'find' ist unregelmäßig: find → found (nicht 'finded').", "find": "Es ist Vergangenheit: find → found." } },
        { typ: "text", frage: "Past tense of 'make': She ___ a cake.", richtig: "made", erklaerung: "make → made (unregelmäßig).", schritte: ["make ist unregelmäßig.", "make → made."], fehler: { "maked": "Unregelmäßig: make → made.", "maled": "make → made (nicht 'maled')." } },
        { typ: "text", frage: "Past tense of 'drive': We ___ to the city.", richtig: "drove", erklaerung: "drive → drove (unregelmäßig).", schritte: ["drive ist unregelmäßig.", "drive → drove."], fehler: { "drived": "Unregelmäßig: drive → drove.", "drive": "Vergangenheit: drive → drove." } },
        { typ: "text", frage: "Past tense of 'go': They ___ to school.", richtig: "went", erklaerung: "go → went (unregelmäßig).", schritte: ["go ist unregelmäßig.", "go → went."], fehler: { "goed": "Unregelmäßig: go → went.", "goes": "Vergangenheit: go → went." } },
        { typ: "text", frage: "Past tense of 'buy': He ___ a new bike.", richtig: "bought", erklaerung: "buy → bought (unregelmäßig).", schritte: ["buy ist unregelmäßig.", "buy → bought."], fehler: { "buyed": "Unregelmäßig: buy → bought.", "buy": "Vergangenheit: bought." } },
        { typ: "mc", frage: "Which is correct? Yesterday I ___ my friend.", antworten: ["meeted", "met", "meet"], richtig: "met", erklaerung: "meet → met (unregelmäßig).", schritte: ["meet ist unregelmäßig.", "meet → met."], fehler: { "meeted": "Unregelmäßig: meet → met (nicht 'meeted').", "meet": "Vergangenheit: met." } },
        { typ: "mc", frage: "The weather ___ nice yesterday.", antworten: ["was", "were"], richtig: "was", erklaerung: "'weather' ist Singular → was.", schritte: ["weather = Einzahl.", "Einzahl → was."], fehler: { "were": "'weather' ist Singular → was." } },
        { typ: "mc", frage: "We ___ at home all day.", antworten: ["was", "were"], richtig: "were", erklaerung: "we → were.", schritte: ["we = Mehrzahl.", "Mehrzahl → were."], fehler: { "was": "Bei 'we' nimmt man were." } },
        { typ: "mc", frage: "How ___ your holidays?", antworten: ["was", "were"], richtig: "were", erklaerung: "'holidays' ist Mehrzahl → were.", schritte: ["holidays = Mehrzahl.", "→ were."], fehler: { "was": "'holidays' ist Mehrzahl → were." } },
        { typ: "text", frage: "Make it negative: 'It was cold.' → 'It ___ cold.'", richtig: "wasn't", akzeptiert: ["was not"], erklaerung: "was + not = wasn't (Singular).", schritte: ["it = Einzahl → was.", "was + not = wasn't."], fehler: { "weren't": "'it' ist Singular → wasn't.", "not was": "Reihenfolge: was + not = wasn't." } },
        { typ: "text", frage: "Make it negative: 'They were happy.' → 'They ___ happy.'", richtig: "weren't", akzeptiert: ["were not"], erklaerung: "were + not = weren't (Mehrzahl).", schritte: ["they = Mehrzahl → were.", "were + not = weren't."], fehler: { "wasn't": "'they' ist Mehrzahl → weren't.", "not were": "Reihenfolge: were + not = weren't." } },
        { typ: "text", frage: "Make it negative: 'She found it.' → 'She ___ find it.'", richtig: "didn't", akzeptiert: ["did not"], erklaerung: "Verneinung im Past: didn't + Grundform (find!).", schritte: ["Verneinung mit didn't.", "Danach die Grundform: didn't find."], fehler: { "didn't found": "Nach 'didn't' kommt die GRUNDFORM: didn't find.", "not found": "Nutze didn't + Grundform: didn't find." } },
        { typ: "mc", frage: "Which is the correct negative? 'I ___ my homework.'", antworten: ["didn't do", "didn't did", "not did"], richtig: "didn't do", erklaerung: "didn't + Grundform (do).", schritte: ["Verneinung: didn't.", "+ Grundform: didn't do."], fehler: { "didn't did": "Nach didn't die Grundform: didn't do.", "not did": "Verneinung im Past: didn't + Grundform." } },
        { typ: "text", frage: "Make it negative: 'We went home.' → 'We ___ go home.'", richtig: "didn't", akzeptiert: ["did not"], erklaerung: "didn't + Grundform (go).", schritte: ["Verneinung: didn't.", "Danach Grundform: didn't go."], fehler: { "didn't went": "Nach didn't die Grundform: didn't go." } },
        { typ: "mc", frage: "We went ___ Disneyland.", antworten: ["to", "in", "at"], richtig: "to", erklaerung: "go TO a place.", schritte: ["Bewegung zu einem Ort.", "go to Disneyland."], fehler: { "in": "Man sagt go TO a place (nicht 'in').", "at": "Bei Bewegung: go to." } },
        { typ: "mc", frage: "We travelled ___ bus.", antworten: ["by", "with", "in"], richtig: "by", erklaerung: "Verkehrsmittel: by bus/car/train.", schritte: ["Verkehrsmittel → by.", "by bus."], fehler: { "with": "Verkehrsmittel: by bus (nicht 'with the bus').", "in": "Man sagt by bus." } },
        { typ: "mc", frage: "Which sentence is correct?", antworten: ["On Saturday I met my friends.", "On Saturday I met with my friends.", "On Saturday I meet my friends."], richtig: "On Saturday I met my friends.", erklaerung: "'meet' braucht kein 'with', und es ist Vergangenheit (met).", schritte: ["meet → met (Vergangenheit).", "Kein 'with' nötig."], fehler: { "On Saturday I met with my friends.": "'meet' braucht kein 'with': I met my friends.", "On Saturday I meet my friends.": "Es ist Vergangenheit: met." } },
        { typ: "freitext", frage: "Correct this sentence: 'Yesterday we drive to the city and I finded my friend.'", kriterien: "beide Verben in der richtigen Simple-Past-Form (drove, found); Satz bleibt sonst sinnvoll und vollständig.", musterloesung: "Yesterday we drove to the city and I found my friend.", tipp: "Achte auf die unregelmäßigen Verben: drive → drove, find → found." },
        { typ: "freitext", frage: "Write 3 sentences about your last weekend. Use the simple past.", kriterien: "drei vollständige Sätze; durchgehend Simple Past; unregelmäßige Verben in der richtigen Form; sinnvoll.", musterloesung: "Last weekend I went to my grandma. We played games and ate some cake. The weather was sunny, so we were happy.", tipp: "Vergangenheit! Denk an went, played, was/were und richtige unregelmäßige Formen." }
      ]
    }
  ]
};

// Vokabeltrainer: Lighthouse Band 1 komplett (Enyas Buch, Units 1-6) - Deutsch -> Englisch.
// Von Hand geprueft: Englisch/Deutsch korrekt zugeordnet (PDF-Textebene war teils vertauscht).
window.SCHULWEG.faecher["englisch-6"].vokabeltrainer = [
  { de: "nett / schön", en: "nice" },
  { de: "treffen / kennenlernen", en: "meet" },
  { de: "der Krebs", en: "crab" },
  { de: "was?", en: "what" },
  { de: "dein/e", en: "your" },
  { de: "der Name", en: "name" },
  { de: "die Klasse", en: "class" },
  { de: "können", en: "can" },
  { de: "und", en: "and" },
  { de: "der Strand", en: "beach" },
  { de: "das Lied / der Song", en: "song" },
  { de: "mein/e", en: "my" },
  { de: "die Lieblingsfarbe", en: "favourite colour", alt: ["favorite color"] },
  { de: "die Farbe", en: "colour", alt: ["color"] },
  { de: "rot", en: "red" },
  { de: "gelb", en: "yellow" },
  { de: "blau", en: "blue" },
  { de: "grün", en: "green" },
  { de: "braun", en: "brown" },
  { de: "orange (Farbe)", en: "orange" },
  { de: "grau", en: "grey", alt: ["gray"] },
  { de: "rosa / pink", en: "pink" },
  { de: "lila / violett", en: "purple" },
  { de: "weiß", en: "white" },
  { de: "schwarz", en: "black" },
  { de: "mögen / gernhaben", en: "like" },
  { de: "der/die Schüler/in", en: "student" },
  { de: "die Sportart / der Sport", en: "sport" },
  { de: "das Hobby", en: "hobby" },
  { de: "der Fußball", en: "football" },
  { de: "die Musik", en: "music" },
  { de: "der Fernseher", en: "TV", alt: ["television"] },
  { de: "auch", en: "too" },
  { de: "tanzen", en: "dance" },
  { de: "spielen", en: "play" },
  { de: "das Spiel", en: "game" },
  { de: "lesen", en: "read" },
  { de: "das Buch", en: "book" },
  { de: "reiten", en: "ride" },
  { de: "schwimmen", en: "swim" },
  { de: "das Tier", en: "animal" },
  { de: "haben", en: "have" },
  { de: "das Pony", en: "pony" },
  { de: "lieben", en: "love" },
  { de: "die Katze", en: "cat" },
  { de: "der Bär", en: "bear" },
  { de: "die Ratte", en: "rat" },
  { de: "der Affe", en: "monkey" },
  { de: "der Vogel", en: "bird" },
  { de: "die Schlange", en: "snake" },
  { de: "der Hund", en: "dog" },
  { de: "das Krokodil", en: "crocodile" },
  { de: "das Kaninchen", en: "rabbit" },
  { de: "der Hamster", en: "hamster" },
  { de: "der Fisch", en: "fish" },
  { de: "der Tiger", en: "tiger" },
  { de: "der Elefant", en: "elephant" },
  { de: "das Haustier", en: "pet" },
  { de: "wild", en: "wild" },
  { de: "das Paar", en: "pair" },
  { de: "das Ding / die Sache", en: "thing" },
  { de: "sich erinnern (an)", en: "remember" },
  { de: "gehen / fahren", en: "go" },
  { de: "der Park", en: "park" },
  { de: "das Fahrrad", en: "bike" },
  { de: "großartig / prima", en: "great" },
  { de: "klein", en: "small" },
  { de: "groß", en: "big" },
  { de: "alt", en: "old" },
  { de: "neu", en: "new" },
  { de: "cool", en: "cool" },
  { de: "die Ferien", en: "holidays" },
  { de: "die Geschichte", en: "story" },
  { de: "Hallo", en: "hello", alt: ["hi"] },
  { de: "nein", en: "no" },
  { de: "weg / fort", en: "away" },
  { de: "dumm / blöd", en: "stupid" },
  { de: "die Möwe", en: "seagull" },
  { de: "helfen / die Hilfe", en: "help" },
  { de: "die Schule", en: "school" },
  { de: "das Geräusch / der Klang", en: "sound" },
  { de: "der Junge", en: "boy" },
  { de: "das Mädchen", en: "girl" },
  { de: "der/die Lehrer/in", en: "teacher" },
  { de: "das Auto", en: "car" },
  { de: "das Handy / Mobiltelefon", en: "mobile", alt: ["mobile phone"] },
  { de: "der Morgen", en: "morning" },
  { de: "gut", en: "good" },
  { de: "der Bruder", en: "brother" },
  { de: "die Schwester", en: "sister" },
  { de: "der/die Freund/in", en: "friend" },
  { de: "das Dorf", en: "village" },
  { de: "nahe / in der Nähe", en: "near" },
  { de: "das Alter", en: "age" },
  { de: "der Raum / das Zimmer", en: "room" },
  { de: "die Kantine / Mensa", en: "canteen" },
  { de: "die Kunst", en: "art" },
  { de: "die Naturwissenschaft", en: "science" },
  { de: "das Labor", en: "lab" },
  { de: "die Sporthalle", en: "sports hall" },
  { de: "der Schulsport", en: "PE" },
  { de: "die (Unterrichts-)Stunde", en: "lesson" },
  { de: "nun / jetzt", en: "now" },
  { de: "wo?", en: "where" },
  { de: "hier", en: "here" },
  { de: "der Stundenplan", en: "timetable" },
  { de: "die Zeit / Uhrzeit", en: "time" },
  { de: "der Montag", en: "Monday" },
  { de: "der Dienstag", en: "Tuesday" },
  { de: "der Mittwoch", en: "Wednesday" },
  { de: "der Donnerstag", en: "Thursday" },
  { de: "der Freitag", en: "Friday" },
  { de: "die Schulversammlung", en: "assembly" },
  { de: "die Technik / Technologie", en: "technology" },
  { de: "die Erdkunde / Geografie", en: "geography" },
  { de: "die Mathematik", en: "maths", alt: ["math"] },
  { de: "die Geschichte (Fach)", en: "history" },
  { de: "Französisch", en: "French" },
  { de: "die Pause", en: "break" },
  { de: "das Mittagessen", en: "lunch" },
  { de: "das Schauspiel", en: "drama" },
  { de: "jeder Tag", en: "every day" },
  { de: "richtig", en: "right" },
  { de: "falsch", en: "wrong" },
  { de: "die (Groß-)Stadt", en: "city" },
  { de: "anfangen / beginnen", en: "start" },
  { de: "mit", en: "with" },
  { de: "das Klassenzimmer", en: "classroom" },
  { de: "ja", en: "yes" },
  { de: "aber", en: "but" },
  { de: "alle", en: "all" },
  { de: "die Leute / Menschen", en: "people" },
  { de: "der Ort / Platz", en: "place" },
  { de: "machen / herstellen", en: "make" },
  { de: "für", en: "for" },
  { de: "der Blazer", en: "blazer" },
  { de: "der Pullover", en: "pullover" },
  { de: "das Hemd", en: "shirt" },
  { de: "der Schuh", en: "shoe" },
  { de: "der Rock", en: "skirt" },
  { de: "die Socke", en: "sock" },
  { de: "die Krawatte", en: "tie" },
  { de: "die Strumpfhose", en: "tights" },
  { de: "die Hose", en: "trousers" },
  { de: "die Uniform", en: "uniform" },
  { de: "wichtig", en: "important" },
  { de: "der/die Schulleiter/in", en: "principal" },
  { de: "hoffen", en: "hope" },
  { de: "froh / glücklich", en: "happy" },
  { de: "bitte", en: "please" },
  { de: "Tut mir leid", en: "sorry" },
  { de: "daheim / zu Hause", en: "at home" },
  { de: "das Zuhause", en: "home" },
  { de: "die Hausaufgabe", en: "homework" },
  { de: "schreiben", en: "write" },
  { de: "wissen / kennen", en: "know" },
  { de: "schlecht / schlimm", en: "bad" },
  { de: "die Idee", en: "idea" },
  { de: "brauchen / benötigen", en: "need" },
  { de: "das Papier", en: "paper" },
  { de: "die Schere", en: "scissors" },
  { de: "sagen", en: "say" },
  { de: "denken / meinen", en: "think" },
  { de: "das Theater", en: "theatre", alt: ["theater"] },
  { de: "die Broschüre", en: "brochure" },
  { de: "zurück", en: "back" },
  { de: "das Pfund", en: "pound" },
  { de: "der Bleistiftanspitzer", en: "pencil sharpener" },
  { de: "der Radiergummi", en: "rubber" },
  { de: "das Lineal", en: "ruler" },
  { de: "der Stift / Kugelschreiber", en: "pen" },
  { de: "der Bleistift", en: "pencil" },
  { de: "das Federmäppchen", en: "pencil case" },
  { de: "der Taschenrechner", en: "calculator" },
  { de: "das Übungsheft", en: "exercise book" },
  { de: "die Übung / Aufgabe", en: "exercise" },
  { de: "das Tagebuch", en: "diary" },
  { de: "der Locher", en: "hole punch" },
  { de: "kaufen", en: "buy" },
  { de: "das Kind", en: "child" },
  { de: "das Netz", en: "network" },
  { de: "der Samstag", en: "Saturday" },
  { de: "der Sonntag", en: "Sunday" },
  { de: "das Wochenende", en: "weekend" },
  { de: "die Schultasche", en: "school bag" },
  { de: "der Ausdruck / die Wendung", en: "phrase" },
  { de: "die Karte", en: "card" },
  { de: "der Kasten / die Kiste", en: "box" },
  { de: "auf Englisch", en: "in English" },
  { de: "sprechen / reden", en: "talk" },
  { de: "(aus)leihen", en: "borrow" },
  { de: "nächste/r", en: "next" },
  { de: "sicher", en: "sure" },
  { de: "Deutsch", en: "German" },
  { de: "buchstabieren", en: "spell" },
  { de: "das Alphabet", en: "alphabet" },
  { de: "die Adresse", en: "address" },
  { de: "die Telefonnummer", en: "phone number" },
  { de: "die Nummer", en: "number" },
  { de: "die Straße (in Orten)", en: "street" },
  { de: "die Straße / Landstraße", en: "road" },
  { de: "das Foto", en: "photo" },
  { de: "das Haus", en: "house" },
  { de: "die Wohnung", en: "flat" },
  { de: "die Küche", en: "kitchen" },
  { de: "das Schlafzimmer", en: "bedroom" },
  { de: "der Garten", en: "garden" },
  { de: "das Wohnzimmer", en: "living room" },
  { de: "Mama / Mutti", en: "mum" },
  { de: "die Mutter", en: "mother" },
  { de: "Papa / Vati", en: "dad" },
  { de: "der Vater", en: "father" },
  { de: "leben / wohnen", en: "live" },
  { de: "der Flur / die Diele", en: "hall" },
  { de: "die Toilette", en: "toilet" },
  { de: "das Badezimmer", en: "bathroom" },
  { de: "die Garage", en: "garage" },
  { de: "der Traum", en: "dream" },
  { de: "die Familie", en: "family" },
  { de: "oben", en: "upstairs" },
  { de: "unten", en: "downstairs" },
  { de: "immer", en: "always" },
  { de: "der Platz / Raum", en: "space" },
  { de: "der Stiefvater", en: "stepdad", alt: ["stepfather"] },
  { de: "die Stiefmutter", en: "stepmum", alt: ["stepmother"] },
  { de: "die Stiefschwester", en: "stepsister" },
  { de: "der Stiefbruder", en: "stepbrother" },
  { de: "vermissen", en: "miss" },
  { de: "echt / wirklich", en: "real" },
  { de: "der/die Partner/in", en: "partner" },
  { de: "süß / niedlich", en: "cute" },
  { de: "der Stammbaum", en: "family tree" },
  { de: "der Baum", en: "tree" },
  { de: "zusammen", en: "together" },
  { de: "der/die Cousin/e", en: "cousin" },
  { de: "die Tante", en: "aunt" },
  { de: "der Onkel", en: "uncle" },
  { de: "die Eltern", en: "parents" },
  { de: "die Großeltern", en: "grandparents" },
  { de: "der Großvater", en: "grandfather" },
  { de: "die Großmutter", en: "grandmother" },
  { de: "das Problem", en: "problem" },
  { de: "unordentlich", en: "messy" },
  { de: "rechthaberisch / herrisch", en: "bossy" },
  { de: "tun / machen", en: "do" },
  { de: "laut", en: "noisy" },
  { de: "der Teppich / Läufer", en: "rug" },
  { de: "der Stuhl", en: "chair" },
  { de: "der Schreibtisch", en: "desk" },
  { de: "das Regal", en: "shelf" },
  { de: "die Lampe", en: "lamp" },
  { de: "der Tisch", en: "table" },
  { de: "das Bett", en: "bed" },
  { de: "das Kissen", en: "cushion" },
  { de: "der Spiegel", en: "mirror" },
  { de: "der Kleiderschrank", en: "wardrobe" },
  { de: "verschieden / anders", en: "different" },
  { de: "die Überraschung", en: "surprise" },
  { de: "müde", en: "tired" },
  { de: "wirklich", en: "really" },
  { de: "streng", en: "strict" },
  { de: "fies / gemein", en: "mean" },
  { de: "zuhören", en: "listen" },
  { de: "die Frage", en: "question" },
  { de: "die Antwort", en: "answer" },
  { de: "einfach / leicht", en: "easy" },
  { de: "schwierig / schwer", en: "difficult" },
  { de: "das Beispiel", en: "example" },
  { de: "die Nachrichten", en: "news" },
  { de: "das Kino", en: "cinema" },
  { de: "anschauen / beobachten", en: "watch" },
  { de: "die Sendung", en: "programme", alt: ["program"] },
  { de: "bald", en: "soon" },
  { de: "das Restaurant", en: "restaurant" },
  { de: "wieder / noch einmal", en: "again" },
  { de: "die Stadt", en: "town" },
  { de: "einsam", en: "lonely" },
  { de: "der Text / die SMS", en: "text" },
  { de: "die Woche", en: "week" },
  { de: "viele / viel", en: "lots" },
  { de: "weil", en: "because" },
  { de: "das Meer", en: "sea" },
  { de: "arbeiten", en: "work" },
  { de: "zumachen / schließen", en: "close" },
  { de: "die Tür", en: "door" },
  { de: "die Seite", en: "page" },
  { de: "oft", en: "often" },
  { de: "der Sommer", en: "summer" },
  { de: "die Feuerwache", en: "fire station" },
  { de: "der Nachname / Familienname", en: "family name" },
  { de: "nie / niemals", en: "never" },
  { de: "das Aquarium", en: "aquarium" },
  { de: "der Markt", en: "market" },
  { de: "das Einkaufszentrum", en: "shopping centre", alt: ["shopping center"] },
  { de: "bleiben", en: "stay" },
  { de: "das Frühstück", en: "breakfast" },
  { de: "jeder / alle", en: "everybody" },
  { de: "zuerst", en: "first" },
  { de: "danach / dann", en: "then" },
  { de: "das Gemüse", en: "vegetables" },
  { de: "langweilig", en: "boring" },
  { de: "die Süßigkeiten", en: "sweets" },
  { de: "der Nachmittag", en: "afternoon" },
  { de: "meistens / normalerweise", en: "usually" },
  { de: "da / dort", en: "there" },
  { de: "der Abend", en: "evening" },
  { de: "manchmal", en: "sometimes" },
  { de: "kommen", en: "come" },
  { de: "das Geschenk", en: "present" },
  { de: "heute", en: "today" },
  { de: "die Turnschuhe", en: "trainers" },
  { de: "teuer", en: "expensive" },
  { de: "der Kapuzenpullover", en: "hoodie" },
  { de: "hassen", en: "hate" },
  { de: "schrecklich / fürchterlich", en: "terrible" },
  { de: "der Monat", en: "month" },
  { de: "Januar", en: "January" },
  { de: "Februar", en: "February" },
  { de: "März", en: "March" },
  { de: "April", en: "April" },
  { de: "Mai", en: "May" },
  { de: "Juni", en: "June" },
  { de: "Juli", en: "July" },
  { de: "August", en: "August" },
  { de: "September", en: "September" },
  { de: "Oktober", en: "October" },
  { de: "November", en: "November" },
  { de: "Dezember", en: "December" },
  { de: "das Datum", en: "date" },
  { de: "wann?", en: "when" },
  { de: "frei", en: "free" },
  { de: "aufstehen", en: "get up" },
  { de: "früh", en: "early" },
  { de: "faul", en: "lazy" },
  { de: "spät", en: "late" },
  { de: "nachts / in der Nacht", en: "at night" },
  { de: "(zu Fuß) gehen", en: "walk" },
  { de: "unglücklich", en: "unhappy" },
  { de: "planen", en: "plan" },
  { de: "etwas", en: "something" },
  { de: "das Konzert", en: "concert" },
  { de: "der Zoo", en: "zoo" },
  { de: "aufgeregt / gespannt", en: "excited" },
  { de: "der Hügel", en: "hill" },
  { de: "schnell", en: "fast" },
  { de: "das Bein", en: "leg" },
  { de: "fallen / hinfallen", en: "fall" },
  { de: "das Krankenhaus", en: "hospital" },
  { de: "oder", en: "or" },
  { de: "das Ende", en: "end" },
  { de: "der (Schluss-)Verkauf", en: "sale" },
  { de: "britisch", en: "British" },
  { de: "das Geld", en: "money" },
  { de: "der Mann", en: "man" },
  { de: "das Sonderangebot", en: "special offer" },
  { de: "besondere/r", en: "special" },
  { de: "derselbe / dieselbe", en: "the same" },
  { de: "probieren / ausprobieren", en: "try" },
  { de: "der Helm", en: "helmet" },
  { de: "die Anzeige / Werbung", en: "advert" },
  { de: "raten / erraten", en: "guess" },
  { de: "die Welt", en: "world" },
  { de: "der/die Besucher/in", en: "visitor" },
  { de: "der Stall / die Scheune", en: "barn" },
  { de: "streicheln", en: "stroke" },
  { de: "der Esel", en: "donkey" },
  { de: "die Ente", en: "duck" },
  { de: "der Teich", en: "pond" },
  { de: "das Feld / die Weide", en: "field" },
  { de: "die Kuh", en: "cow" },
  { de: "das Schwein", en: "pig" },
  { de: "das Schaf", en: "sheep" },
  { de: "das Huhn / Hähnchen", en: "chicken" },
  { de: "das Leben", en: "life" },
  { de: "der Wecker", en: "alarm clock" },
  { de: "wecken", en: "wake" },
  { de: "andere/r", en: "other" },
  { de: "draußen", en: "outside" },
  { de: "drinnen", en: "inside" },
  { de: "füttern", en: "feed" },
  { de: "sich fertig machen", en: "get ready" },
  { de: "essen / fressen", en: "eat" },
  { de: "ungefähr", en: "about" },
  { de: "sich kümmern um", en: "look after" },
  { de: "Sport treiben", en: "do sport" },
  { de: "nichts", en: "nothing" },
  { de: "sitzen", en: "sit" },
  { de: "das Jahr", en: "year" },
  { de: "der Dialog", en: "dialogue" },
  { de: "das Gefühl", en: "feeling" },
  { de: "die Diskussion", en: "discussion" },
  { de: "sich fühlen", en: "feel" },
  { de: "ein bisschen", en: "a bit" },
  { de: "der Rollstuhl", en: "wheelchair" },
  { de: "normal / gewöhnlich", en: "normal" },
  { de: "gewinnen", en: "win" },
  { de: "fragen", en: "ask" },
  { de: "das Getränk / trinken", en: "drink" },
  { de: "verstehen", en: "understand" },
  { de: "sprechen", en: "speak" },
  { de: "der Mund", en: "mouth" },
  { de: "flauschig / pelzig", en: "furry" },
  { de: "interessant", en: "interesting" },
  { de: "der Käfig", en: "cage" },
  { de: "warum?", en: "why" },
  { de: "freundlich", en: "friendly" },
  { de: "die Schulter", en: "shoulder" },
  { de: "das Obst", en: "fruit" },
  { de: "die Nuss", en: "nut" },
  { de: "schlafen", en: "sleep" },
  { de: "finden", en: "find" },
  { de: "der Bus", en: "bus" },
  { de: "nervös / aufgeregt", en: "nervous" },
  { de: "das Abenteuer", en: "adventure" },
  { de: "das Land", en: "country" },
  { de: "die Szene", en: "scene" },
  { de: "einladen", en: "invite" },
  { de: "die Schlafparty", en: "sleepover" },
  { de: "bringen / mitbringen", en: "bring" },
  { de: "der Schlafsack", en: "sleeping bag" },
  { de: "nass", en: "wet" },
  { de: "lachen", en: "laugh" },
  { de: "durch", en: "through" },
  { de: "hungrig sein", en: "be hungry" },
  { de: "gefährlich", en: "dangerous" },
  { de: "der Lärm", en: "noise" },
  { de: "nur / bloß", en: "only" },
  { de: "das Zeichen / Schild", en: "sign" },
  { de: "links", en: "left" },
  { de: "rechts", en: "right" },
  { de: "die Einladung", en: "invitation" },
  { de: "das Picknick", en: "picnic" },
  { de: "benutzen / verwenden", en: "use" },
  { de: "das Wörterbuch", en: "dictionary" },
  { de: "das Gedicht", en: "poem" },
  { de: "der Hafen", en: "harbour", alt: ["harbor"] },
  { de: "das Café", en: "cafe" },
  { de: "die Fähre", en: "ferry" },
  { de: "die Pommes frites", en: "chips" },
  { de: "der Salat", en: "salad" },
  { de: "die Suppe", en: "soup" },
  { de: "die Flasche", en: "bottle" },
  { de: "das Wasser", en: "water" },
  { de: "die Tasse", en: "cup" },
  { de: "der Kaffee", en: "coffee" },
  { de: "der Tee", en: "tea" },
  { de: "klingeln / läuten", en: "ring" },
  { de: "der Job / die Stelle", en: "job" },
  { de: "beschäftigt sein", en: "be busy" },
  { de: "kochen", en: "cook" },
  { de: "abwaschen", en: "wash up" },
  { de: "müssen", en: "must" },
  { de: "hart arbeiten", en: "work hard" },
  { de: "der Brief", en: "letter" },
  { de: "besorgt / beunruhigt", en: "worried" },
  { de: "im Moment", en: "at the moment" },
  { de: "anrufen", en: "phone" },
  { de: "geschehen / passieren", en: "happen" },
  { de: "einen Kopfsprung machen", en: "dive" },
  { de: "verstecken", en: "hide" },
  { de: "schicken / senden", en: "send" },
  { de: "die Gitarre", en: "guitar" },
  { de: "lernen", en: "learn" },
  { de: "das Schlagzeug", en: "drums" },
  { de: "die Gruppe", en: "group" },
  { de: "das Instrument", en: "instrument" },
  { de: "jung", en: "young" },
  { de: "der/die Musiker/in", en: "musician" },
  { de: "der/die Sänger/in", en: "singer" },
  { de: "singen", en: "sing" },
  { de: "das Klavier", en: "piano" },
  { de: "den Tisch decken", en: "set the table" },
  { de: "sauber machen / putzen", en: "clean" },
  { de: "klein (winzig)", en: "little" },
  { de: "vielleicht", en: "maybe" },
  { de: "der/die Koch/Köchin", en: "cook" },
  { de: "die Form", en: "form" },
  { de: "das Essen / Lebensmittel", en: "food" },
  { de: "das Fenster", en: "window" },
  { de: "hören", en: "hear" },
  { de: "der Unterschied", en: "difference" },
  { de: "einige / ein paar", en: "some" },
  { de: "der (Sitz-)Platz", en: "seat" },
  { de: "das Gesicht", en: "face" },
  { de: "die (feste) Freundin", en: "girlfriend" },
  { de: "der (feste) Freund", en: "boyfriend" },
  { de: "schwer / hart", en: "hard" },
  { de: "stolz (auf)", en: "proud" },
  { de: "wahr", en: "true" },
  { de: "falsch (nicht wahr)", en: "false" },
  { de: "beschreiben", en: "describe" },
  { de: "neben", en: "next to" },
  { de: "zwischen", en: "between" },
  { de: "hinter", en: "behind" },
  { de: "unter", en: "under" },
  { de: "vor", en: "in front of" },
  { de: "der Apfel", en: "apple" },
  { de: "das Rezept", en: "recipe" },
  { de: "die Marmelade", en: "jam" },
  { de: "die Sahne", en: "cream" },
  { de: "das Paddelboot / Kanu", en: "canoe" },
  { de: "der Themenpark", en: "theme park" },
  { de: "der Badeanzug", en: "swimsuit" },
  { de: "die Badehose", en: "swimming trunks" },
  { de: "das Handtuch", en: "towel" },
  { de: "die Sonnenbrille", en: "sunglasses" },
  { de: "der Hut", en: "hat" },
  { de: "die (Kartoffel-)Chips", en: "crisps" },
  { de: "das Würstchen / die Wurst", en: "sausage" },
  { de: "die Apfelsine", en: "orange" },
  { de: "die Schokolade", en: "chocolate" },
  { de: "der Keks", en: "biscuit" },
  { de: "der Lautsprecher", en: "speaker" },
  { de: "der Schwimmreifen", en: "tube" },
  { de: "der (Regen-)Schirm", en: "umbrella" },
  { de: "die Sonnencreme", en: "suncream" },
  { de: "die Decke", en: "blanket" },
  { de: "vergessen", en: "forget" },
  { de: "die Kette", en: "chain" },
  { de: "an Bord", en: "aboard" },
  { de: "die Flaschenpost", en: "message in a bottle" },
  { de: "die Frau", en: "woman" },
  { de: "der/die Schmuggler/in", en: "smuggler" },
  { de: "tun / legen / stellen", en: "put" },
  { de: "besser", en: "better" },
  { de: "die Minute", en: "minute" },
  { de: "sich beeilen", en: "hurry" },
  { de: "der Platz (in der Stadt)", en: "square" },
  { de: "der Stadtplan / die Landkarte", en: "map" },
  { de: "noch ein/e", en: "another" },
  { de: "folgen / verfolgen", en: "follow" },
  { de: "schieben", en: "push" },
  { de: "die Uhr", en: "clock" },
  { de: "schnell (rasch)", en: "quick" },
  { de: "langsam", en: "slow" },
  { de: "heiß", en: "hot" },
  { de: "das Eis", en: "ice cream" },
  { de: "warten (auf)", en: "wait" },
  { de: "die Tochter", en: "daughter" },
  { de: "herauskommen", en: "get out" },
  { de: "unheimlich", en: "scary" },
  { de: "fliegen", en: "fly" }
];
