/*
 * Englisch Klasse 6 - Klausurvorbereitung (Theme 5: will/won't, Wetter,
 * Adverbien, Bahnhof, E-Mail). Aufgaben aus ChatGPT-Analyse, von Claude
 * auf App-Schema geprueft/korrigiert. Eigene Aufgaben, keine Buchkopien.
 *
 * Typen: "mc" | "text" (eindeutige Antwort, Gross/Klein egal) |
 *        "freitext" (freie Antwort -> KI gibt Feedback, kein richtig/falsch)
 */
window.SCHULWEG = window.SCHULWEG || { faecher: {} };

window.SCHULWEG.faecher["englisch-6"] = {
  fach: "Englisch",
  klasse: 6,
  farbe: "englisch",
  icon: "🇬🇧",
  themen: [
    {
      id: "klausur-theme5",
      titel: "Klausurvorbereitung (Theme 5)",
      seiten: "S.94–96, 106–107, 157",
      voraussetzung: "einfache Zukunftssätze mit 'I'll' und den wichtigsten Wortschatz",
      intro:
        "Diese Übungen sind genau auf deine Klassenarbeit zugeschnitten: will/won't, Wetter, Adverbien, Bahnhof und das E-Mail-Schreiben. Sie werden langsam schwerer.",
      aufgaben: [
        {
          typ: "mc",
          frage: "Tomorrow it ____ rain.",
          antworten: ["will", "won't", "is"],
          richtig: "will",
          erklaerung: "Für Vorhersagen in der Zukunft nutzt du 'will'.",
          schritte: ["Achte auf 'Tomorrow' → Zukunft.", "Nutze 'will'."],
          fehler: {
            "won't": "'won't' heißt, dass etwas NICHT passiert. Hier ist eine normale Vorhersage gemeint → will.",
            "is": "'is' ist Gegenwart. Für morgen brauchst du die Zukunft mit 'will'."
          }
        },
        {
          typ: "text",
          frage: "Complete: I think it ___ (be) sunny tomorrow.",
          richtig: "will be",
          erklaerung: "Nach 'I think' und für morgen nutzt du will + Grundform: 'will be'.",
          schritte: ["Denke an die Zukunft (tomorrow).", "Setze 'will be' ein."],
          fehler: {
            "is": "Das ist Gegenwart. Für morgen brauchst du 'will be'.",
            "be": "'be' allein reicht nicht – es fehlt 'will'.",
            "will": "Es fehlt das 'be': richtig ist 'will be'."
          }
        },
        {
          typ: "mc",
          frage: "Choose the correct word: She runs ____.",
          antworten: ["quick", "quickly", "careful"],
          richtig: "quickly",
          erklaerung: "Wie jemand etwas tut, beschreibt ein Adverb (oft mit -ly).",
          schritte: ["Suche das Verb: runs.", "Beschreibe das Verb mit einem Adverb: quickly."],
          fehler: {
            "quick": "'quick' ist ein Adjektiv. Für das Verb brauchst du das Adverb 'quickly'.",
            "careful": "Passt inhaltlich nicht – und ist außerdem ein Adjektiv."
          }
        },
        {
          typ: "text",
          frage: "Complete: He is very ___ (careful / carefully) with his work.",
          richtig: "careful",
          erklaerung: "Nach 'is' (Form von to be) steht ein Adjektiv.",
          schritte: ["Erkenne to be: 'is'.", "Nach to be nutzt du ein Adjektiv: careful."],
          fehler: {
            "carefully": "Nach 'is' braucht man ein Adjektiv, kein Adverb – also 'careful'."
          }
        },
        {
          typ: "mc",
          frage: "Which word belongs to the train station?",
          antworten: ["platform", "snow", "tent"],
          richtig: "platform",
          erklaerung: "'platform' (Bahnsteig) gehört zum Bahnhof.",
          schritte: ["Denke an den Bahnhof.", "Wähle das passende Wort."],
          fehler: {
            "snow": "'snow' (Schnee) gehört zum Wetter.",
            "tent": "'tent' (Zelt) gehört zum Camping."
          }
        },
        {
          typ: "text",
          frage: "Complete: The train ___ (leave) from Platform 4 at 9 a.m.",
          richtig: "leaves",
          erklaerung: "Feste Fahrpläne stehen im Simple Present – bei 'the train' (it) mit -s.",
          schritte: ["Es geht um einen Fahrplan → Simple Present.", "Bei 'the train' (it) kommt ein -s dran: leaves."],
          fehler: {
            "leave": "Bei 'the train' (it) fehlt das -s: richtig ist 'leaves'.",
            "will leave": "Bei einem festen Fahrplan nimmt man das Simple Present: 'leaves'."
          }
        },
        {
          typ: "mc",
          frage: "It's minus five degrees. It's ____.",
          antworten: ["windy", "freezing", "sunny"],
          richtig: "freezing",
          erklaerung: "Bei Minusgraden ist es eiskalt: freezing.",
          schritte: ["Lies die Temperatur: minus five.", "Wähle das Wort für eiskalt: freezing."],
          fehler: {
            "windy": "'windy' (windig) sagt nichts über die Temperatur.",
            "sunny": "'sunny' (sonnig) passt nicht zu minus fünf Grad."
          }
        },
        {
          typ: "text",
          frage: "Complete: I hope it ___ rain tomorrow.",
          richtig: "won't",
          akzeptiert: ["will not"],
          erklaerung: "Wenn du hoffst, dass etwas NICHT passiert, nutzt du 'won't' (= will not).",
          schritte: ["Achte auf 'I hope' – du wünschst dir etwas.", "Du willst KEINEN Regen → won't."],
          fehler: {
            "will": "'will' würde heißen, dass es regnet – das Gegenteil von dem, was man hofft.",
            "will not": "Richtig gedacht! Schreib nur die Kurzform: won't.",
            "doesn't": "Es geht um morgen (Zukunft): nutze 'won't'."
          }
        },
        {
          typ: "mc",
          frage: "Look at the dark clouds! It ____ rain soon.",
          antworten: ["will", "won't", "does"],
          richtig: "will",
          erklaerung: "Anzeichen wie dunkle Wolken → Vorhersage mit will.",
          schritte: ["Dunkle Wolken = Anzeichen für Regen.", "Vorhersage mit 'will'."],
          fehler: {
            "won't": "Dunkle Wolken heißt: Es WIRD regnen. 'won't' wäre das Gegenteil.",
            "does": "'does' passt hier nicht – für eine Vorhersage nutzt du 'will'."
          }
        },
        {
          typ: "text",
          frage: "Make it negative: 'It will snow.' → 'It ___ snow.'",
          richtig: "won't",
          akzeptiert: ["will not"],
          erklaerung: "Die Verneinung von 'will' ist 'won't' (= will not).",
          schritte: ["will + not = won't.", "'It won't snow.'"],
          fehler: {
            "will": "Du sollst den Satz VERNEINEN: won't.",
            "doesn't": "Die Verneinung der Zukunft ist won't, nicht doesn't."
          }
        },
        {
          typ: "text",
          frage: "Adverb of 'slow' = ___",
          richtig: "slowly",
          erklaerung: "Aus dem Adjektiv 'slow' wird mit -ly das Adverb 'slowly'.",
          schritte: ["Adjektiv: slow.", "+ -ly = slowly."],
          fehler: {
            "slow": "Das ist das Adjektiv. Das Adverb ist slowly.",
            "slowley": "Fast! Die richtige Schreibweise ist slowly."
          }
        },
        {
          typ: "mc",
          frage: "He speaks very ____.",
          antworten: ["quiet", "quietly", "quietness"],
          richtig: "quietly",
          erklaerung: "Wie er spricht (Verb) → Adverb: quietly.",
          schritte: ["Verb: speaks.", "Beschreibe es mit einem Adverb: quietly."],
          fehler: {
            "quiet": "'quiet' ist ein Adjektiv. Das Verb 'speaks' braucht ein Adverb: quietly.",
            "quietness": "Das ist ein Nomen (die Stille)."
          }
        },
        {
          typ: "text",
          frage: "Complete: She is a ___ (careful / carefully) driver.",
          richtig: "careful",
          erklaerung: "Vor einem Nomen ('driver') steht ein Adjektiv.",
          schritte: ["'driver' ist ein Nomen.", "Davor steht ein Adjektiv: careful."],
          fehler: {
            "carefully": "Vor dem Nomen 'driver' steht ein Adjektiv: careful (nicht das Adverb)."
          }
        },
        {
          typ: "mc",
          frage: "She sings ____.",
          antworten: ["beautiful", "beautifully"],
          richtig: "beautifully",
          erklaerung: "Wie sie singt (Verb) → Adverb: beautifully.",
          schritte: ["Verb: sings.", "Adverb dazu: beautifully."],
          fehler: {
            "beautiful": "'beautiful' ist ein Adjektiv. Das Verb 'sings' braucht ein Adverb: beautifully."
          }
        },
        {
          typ: "mc",
          frage: "There is a lot of wind today. It's ____.",
          antworten: ["foggy", "windy", "hot"],
          richtig: "windy",
          erklaerung: "Viel Wind → it's windy.",
          schritte: ["Wind = wind.", "windig = windy."],
          fehler: {
            "foggy": "'foggy' heißt neblig.",
            "hot": "'hot' heißt heiß – das passt nicht zu Wind."
          }
        },
        {
          typ: "mc",
          frage: "I can't see far. There is a lot of ____.",
          antworten: ["fog", "sun", "snow"],
          richtig: "fog",
          erklaerung: "Schlechte Sicht → Nebel (fog).",
          schritte: ["Man sieht schlecht.", "Das Wort dafür ist fog (Nebel)."],
          fehler: {
            "sun": "Bei Sonne sieht man gut.",
            "snow": "Schnee ist möglich, aber das Wort für schlechte Sicht ist fog."
          }
        },
        {
          typ: "text",
          frage: "Translate into English: 'bewölkt' = ___",
          richtig: "cloudy",
          erklaerung: "Wolke = cloud, bewölkt = cloudy.",
          schritte: ["Wolke = cloud.", "bewölkt = cloudy."],
          fehler: {
            "clody": "Fast! Die Schreibweise ist cloudy.",
            "windy": "'windy' heißt windig, nicht bewölkt."
          }
        },
        {
          typ: "mc",
          frage: "You need a ____ to travel by train.",
          antworten: ["ticket", "tent", "towel"],
          richtig: "ticket",
          erklaerung: "Zum Bahnfahren brauchst du eine Fahrkarte: ticket.",
          schritte: ["Denke an den Bahnhof.", "Fahrkarte = ticket."],
          fehler: {
            "tent": "'tent' (Zelt) gehört zum Camping.",
            "towel": "'towel' heißt Handtuch."
          }
        },
        {
          typ: "text",
          frage: "Opposite of 'to arrive' (at the station) = to ___",
          richtig: "leave",
          akzeptiert: ["depart"],
          erklaerung: "ankommen = arrive, abfahren = leave (oder depart).",
          schritte: ["arrive = ankommen.", "Das Gegenteil ist leave (abfahren)."],
          fehler: {
            "arrive": "Das ist dasselbe Wort – das Gegenteil ist leave.",
            "go": "Zu allgemein. Am Bahnhof sagt man leave (oder depart)."
          }
        },
        {
          typ: "freitext",
          frage: "Finish with your own idea: 'I'll take my rain gear because ___.' (Schreibe einen ganzen Grund.)",
          musterloesung: "I'll take my rain gear because it will rain.",
          tipp: "Am besten mit 'will', z. B. 'because it will rain'."
        },
        {
          typ: "freitext",
          frage: "Write one sentence about your weekend: 'On Saturday I'll ___.'",
          musterloesung: "On Saturday I'll play football with my friends.",
          tipp: "Beginne mit 'On Saturday I'll' und schreibe einen ganzen Satz."
        },
        {
          typ: "freitext",
          frage: "Write one sentence with a reason: 'I think I'll ___ because ___.'",
          musterloesung: "I think I'll stay at home because it will rain.",
          tipp: "Verbinde eine Zukunftsabsicht (I'll …) mit einem Grund (because …)."
        },
        {
          typ: "freitext",
          frage: "Mini-E-Mail (4 Sätze): Erzähle deiner Freundin/deinem Freund vom nächsten Wochenende. Benutze: I'll, won't, because und ein Wetterwort.",
          musterloesung: "Hi! Next weekend I'll go camping with my family. I hope it won't rain because we want to hike. It will be sunny, so I'll take my sunglasses. See you soon!",
          tipp: "Schreibe 4 ganze Sätze und benutze alle vier: I'll, won't, because und ein Wetterwort."
        },
        {
          typ: "freitext",
          frage: "Write a weather forecast for tomorrow (2 sentences). Use 'will' and at least one weather word.",
          musterloesung: "Tomorrow it will be cloudy in the morning. In the afternoon it will be sunny and warm.",
          tipp: "Nutze 'will' und mindestens ein Wetterwort (sunny, cloudy, windy …)."
        }
      ]
    },
    {
      id: "durchsagen",
      titel: "Bahnhof: Durchsagen verstehen",
      seiten: "S.100",
      voraussetzung: "Bahnhofswortschatz (platform, train, leave …)",
      intro: "Lies die Durchsage genau und beantworte die Frage. So übst du, das Wichtigste herauszuhören – hier zum Lesen.",
      aufgaben: [
        {
          typ: "text",
          frage: "Announcement: 'The train to London leaves from platform 3.' — From which platform does the train leave? (number)",
          richtig: "3",
          erklaerung: "platform = Gleis/Bahnsteig. Hier: platform 3.",
          schritte: ["Suche das Wort 'platform' in der Durchsage.", "Dahinter steht die Zahl: 3."]
        },
        {
          typ: "text",
          frage: "Announcement: 'The train to Manchester is delayed by 10 minutes.' — How many minutes is the delay? (number)",
          richtig: "10",
          erklaerung: "delayed = verspätet. 10 minutes = 10 Minuten.",
          schritte: ["'delayed' = Verspätung.", "Suche die Zahl der Minuten: 10."]
        },
        {
          typ: "mc",
          frage: "Announcement: 'The 8 o'clock train to Bristol has been cancelled.' — What happened to the train?",
          antworten: ["It is cancelled.", "It is delayed.", "It is on time."],
          richtig: "It is cancelled.",
          erklaerung: "cancelled = fällt aus / gestrichen.",
          schritte: ["Suchwort: cancelled.", "cancelled = fällt aus."],
          fehler: {
            "It is delayed.": "'delayed' wäre verspätet. Hier steht 'cancelled' = fällt aus.",
            "It is on time.": "'cancelled' heißt, der Zug fährt gar nicht."
          }
        },
        {
          typ: "mc",
          frage: "Announcement: 'The next train to York will leave from platform 5.' — Where does the train leave from?",
          antworten: ["Platform 3", "Platform 5", "Platform 15"],
          richtig: "Platform 5",
          erklaerung: "In der Durchsage steht 'platform 5'.",
          schritte: ["Suche 'platform'.", "platform 5."],
          fehler: {
            "Platform 3": "In der Durchsage steht platform 5, nicht 3.",
            "Platform 15": "Es ist platform 5, nicht 15."
          }
        },
        {
          typ: "mc",
          frage: "Announcement: 'The train from Edinburgh is now arriving at platform 2.' — What is happening?",
          antworten: ["A train is arriving.", "A train is leaving.", "A train is cancelled."],
          richtig: "A train is arriving.",
          erklaerung: "arriving = ankommend – der Zug kommt gerade an.",
          schritte: ["Suchwort: arriving.", "arrive = ankommen."],
          fehler: {
            "A train is leaving.": "Abfahren wäre 'leaving' / 'departing'. Hier: 'arriving' = ankommen.",
            "A train is cancelled.": "Ausfallen wäre 'cancelled'. Hier kommt der Zug an."
          }
        },
        {
          typ: "mc",
          frage: "Announcement: 'Please mind the gap between the train and the platform.' — What should you watch out for?",
          antworten: ["The gap between the train and the platform.", "Your ticket.", "The weather."],
          richtig: "The gap between the train and the platform.",
          erklaerung: "mind the gap = Achte auf den Spalt (zwischen Zug und Bahnsteig).",
          schritte: ["mind = achte auf.", "gap = Spalt/Lücke."],
          fehler: {
            "Your ticket.": "Von einem Ticket ist hier nicht die Rede.",
            "The weather.": "Es geht um den Spalt am Bahnsteig, nicht ums Wetter."
          }
        },
        {
          typ: "text",
          frage: "Announcement: 'The train to Leeds leaves at a quarter to four.' — What time does the train leave? (e.g. 6:15)",
          richtig: "3:45",
          akzeptiert: ["15:45", "quarter to four", "a quarter to four"],
          erklaerung: "a quarter to four = Viertel vor vier = 3:45 (oder 15:45).",
          schritte: ["quarter to = 15 Minuten vor der vollen Stunde.", "quarter to four = 3:45."]
        },
        {
          typ: "mc",
          frage: "Which word means the train comes LATER than planned?",
          antworten: ["delayed", "cancelled", "on time"],
          richtig: "delayed",
          erklaerung: "delayed = verspätet (kommt später).",
          schritte: ["delay = Verzögerung.", "delayed = verspätet."],
          fehler: {
            "cancelled": "'cancelled' heißt: der Zug fällt ganz aus.",
            "on time": "'on time' heißt pünktlich."
          }
        }
      ]
    },
    {
      id: "aufarbeitung",
      titel: "Aufarbeitung: deine Lernfelder",
      seiten: "gezielt aus deinen letzten Arbeiten",
      voraussetzung: "Grundwortschatz – wir schließen gezielt Lücken",
      intro: "Diese Übungen sind genau auf deine letzten Englischarbeiten zugeschnitten: Simple Past (auch unregelmäßige Verben), was/were und die Verneinung, und die richtigen Präpositionen. Keine Sorge – das kriegen wir Stück für Stück hin.",
      aufgaben: [
        { typ: "text", frage: "Past tense of 'find': Yesterday I ___ my keys.", richtig: "found", erklaerung: "'find' ist unregelmäßig: find → found.", schritte: ["find ist unregelmäßig.", "find → found."], fehler: { "finded": "'find' ist unregelmäßig: find → found (nicht 'finded').", "find": "Es ist Vergangenheit: find → found." } },
        { typ: "text", frage: "Past tense of 'make': She ___ a cake.", richtig: "made", erklaerung: "make → made (unregelmäßig).", schritte: ["make ist unregelmäßig.", "make → made."], fehler: { "maked": "Unregelmäßig: make → made.", "maled": "make → made (nicht 'maled')." } },
        { typ: "text", frage: "Past tense of 'drive': We ___ to the city.", richtig: "drove", erklaerung: "drive → drove (unregelmäßig).", schritte: ["drive ist unregelmäßig.", "drive → drove."], fehler: { "drived": "Unregelmäßig: drive → drove.", "drive": "Vergangenheit: drive → drove." } },
        { typ: "text", frage: "Past tense of 'go': They ___ to school.", richtig: "went", erklaerung: "go → went (unregelmäßig).", schritte: ["go ist unregelmäßig.", "go → went."], fehler: { "goed": "Unregelmäßig: go → went.", "goes": "Vergangenheit: go → went." } },
        { typ: "text", frage: "Past tense of 'buy': He ___ a new bike.", richtig: "bought", erklaerung: "buy → bought (unregelmäßig).", schritte: ["buy ist unregelmäßig.", "buy → bought."], fehler: { "buyed": "Unregelmäßig: buy → bought.", "buy": "Vergangenheit: bought." } },
        { typ: "mc", frage: "Which is correct? Yesterday I ___ my friend.", antworten: ["meeted", "met", "meet"], richtig: "met", erklaerung: "meet → met (unregelmäßig).", schritte: ["meet ist unregelmäßig.", "meet → met."], fehler: { "meeted": "Unregelmäßig: meet → met (nicht 'meeted').", "meet": "Vergangenheit: met." } },
        { typ: "mc", frage: "The weather ___ nice yesterday.", antworten: ["was", "were"], richtig: "was", erklaerung: "'weather' ist Singular → was.", schritte: ["weather = Einzahl.", "Einzahl → was."], fehler: { "were": "'weather' ist Singular → was." } },
        { typ: "mc", frage: "We ___ at home all day.", antworten: ["was", "were"], richtig: "were", erklaerung: "we → were.", schritte: ["we = Mehrzahl.", "Mehrzahl → were."], fehler: { "was": "Bei 'we' nimmt man were." } },
        { typ: "mc", frage: "How ___ your holidays?", antworten: ["was", "were"], richtig: "were", erklaerung: "'holidays' ist Mehrzahl → were.", schritte: ["holidays = Mehrzahl.", "→ were."], fehler: { "was": "'holidays' ist Mehrzahl → were." } },
        { typ: "text", frage: "Make it negative: 'It was cold.' → 'It ___ cold.'", richtig: "wasn't", akzeptiert: ["was not"], erklaerung: "was + not = wasn't (Singular).", schritte: ["it = Einzahl → was.", "was + not = wasn't."], fehler: { "weren't": "'it' ist Singular → wasn't.", "not was": "Reihenfolge: was + not = wasn't." } },
        { typ: "text", frage: "Make it negative: 'They were happy.' → 'They ___ happy.'", richtig: "weren't", akzeptiert: ["were not"], erklaerung: "were + not = weren't (Mehrzahl).", schritte: ["they = Mehrzahl → were.", "were + not = weren't."], fehler: { "wasn't": "'they' ist Mehrzahl → weren't.", "not were": "Reihenfolge: were + not = weren't." } },
        { typ: "text", frage: "Make it negative: 'She found it.' → 'She ___ find it.'", richtig: "didn't", akzeptiert: ["did not"], erklaerung: "Verneinung im Past: didn't + Grundform (find!).", schritte: ["Verneinung mit didn't.", "Danach die Grundform: didn't find."], fehler: { "didn't found": "Nach 'didn't' kommt die GRUNDFORM: didn't find.", "not found": "Nutze didn't + Grundform: didn't find." } },
        { typ: "mc", frage: "Which is the correct negative? 'I ___ my homework.'", antworten: ["didn't do", "didn't did", "not did"], richtig: "didn't do", erklaerung: "didn't + Grundform (do).", schritte: ["Verneinung: didn't.", "+ Grundform: didn't do."], fehler: { "didn't did": "Nach didn't die Grundform: didn't do.", "not did": "Verneinung im Past: didn't + Grundform." } },
        { typ: "text", frage: "Make it negative: 'We went home.' → 'We ___ go home.'", richtig: "didn't", akzeptiert: ["did not"], erklaerung: "didn't + Grundform (go).", schritte: ["Verneinung: didn't.", "Danach Grundform: didn't go."], fehler: { "didn't went": "Nach didn't die Grundform: didn't go." } },
        { typ: "mc", frage: "We went ___ Disneyland.", antworten: ["to", "in", "at"], richtig: "to", erklaerung: "go TO a place.", schritte: ["Bewegung zu einem Ort.", "go to Disneyland."], fehler: { "in": "Man sagt go TO a place (nicht 'in').", "at": "Bei Bewegung: go to." } },
        { typ: "mc", frage: "We travelled ___ bus.", antworten: ["by", "with", "in"], richtig: "by", erklaerung: "Verkehrsmittel: by bus/car/train.", schritte: ["Verkehrsmittel → by.", "by bus."], fehler: { "with": "Verkehrsmittel: by bus (nicht 'with the bus').", "in": "Man sagt by bus." } },
        { typ: "mc", frage: "Which sentence is correct?", antworten: ["On Saturday I met my friends.", "On Saturday I met with my friends.", "On Saturday I meet my friends."], richtig: "On Saturday I met my friends.", erklaerung: "'meet' braucht kein 'with', und es ist Vergangenheit (met).", schritte: ["meet → met (Vergangenheit).", "Kein 'with' nötig."], fehler: { "On Saturday I met with my friends.": "'meet' braucht kein 'with': I met my friends.", "On Saturday I meet my friends.": "Es ist Vergangenheit: met." } },
        { typ: "freitext", frage: "Correct this sentence: 'Yesterday we drive to the city and I finded my friend.'", kriterien: "beide Verben in der richtigen Simple-Past-Form (drove, found); Satz bleibt sonst sinnvoll und vollständig.", musterloesung: "Yesterday we drove to the city and I found my friend.", tipp: "Achte auf die unregelmäßigen Verben: drive → drove, find → found." },
        { typ: "freitext", frage: "Write 3 sentences about your last weekend. Use the simple past.", kriterien: "drei vollständige Sätze; durchgehend Simple Past; unregelmäßige Verben in der richtigen Form; sinnvoll.", musterloesung: "Last weekend I went to my grandma. We played games and ate some cake. The weather was sunny, so we were happy.", tipp: "Vergangenheit! Denk an went, played, was/were und richtige unregelmäßige Formen." }
      ]
    }
  ]
};

// Vokabeltrainer: Lighthouse Band 1 + Band 2 komplett (Enyas Buecher) - Deutsch -> Englisch.
// Von Hand geprueft: Englisch/Deutsch korrekt zugeordnet (PDF-Textebene war teils vertauscht).
window.SCHULWEG.faecher["englisch-6"].vokabeltrainer = [
  { id: "en6_0001", de: "nett / schön", en: "nice" },
  { id: "en6_0002", de: "treffen / kennenlernen", en: "meet" },
  { id: "en6_0003", de: "der Krebs", en: "crab" },
  { id: "en6_0004", de: "was?", en: "what" },
  { id: "en6_0005", de: "dein/e", en: "your" },
  { id: "en6_0006", de: "der Name", en: "name" },
  { id: "en6_0007", de: "die Klasse", en: "class" },
  { id: "en6_0008", de: "können", en: "can" },
  { id: "en6_0009", de: "und", en: "and" },
  { id: "en6_0010", de: "der Strand", en: "beach" },
  { id: "en6_0011", de: "das Lied / der Song", en: "song" },
  { id: "en6_0012", de: "mein/e", en: "my" },
  { id: "en6_0013", de: "die Lieblingsfarbe", en: "favourite colour", alt: ["favorite color"] },
  { id: "en6_0014", de: "die Farbe", en: "colour", alt: ["color"] },
  { id: "en6_0015", de: "rot", en: "red" },
  { id: "en6_0016", de: "gelb", en: "yellow" },
  { id: "en6_0017", de: "blau", en: "blue" },
  { id: "en6_0018", de: "grün", en: "green" },
  { id: "en6_0019", de: "braun", en: "brown" },
  { id: "en6_0020", de: "orange (Farbe)", en: "orange" },
  { id: "en6_0021", de: "grau", en: "grey", alt: ["gray"] },
  { id: "en6_0022", de: "rosa / pink", en: "pink" },
  { id: "en6_0023", de: "lila / violett", en: "purple" },
  { id: "en6_0024", de: "weiß", en: "white" },
  { id: "en6_0025", de: "schwarz", en: "black" },
  { id: "en6_0026", de: "mögen / gernhaben", en: "like" },
  { id: "en6_0027", de: "der/die Schüler/in", en: "student" },
  { id: "en6_0028", de: "die Sportart / der Sport", en: "sport" },
  { id: "en6_0029", de: "das Hobby", en: "hobby" },
  { id: "en6_0030", de: "der Fußball", en: "football" },
  { id: "en6_0031", de: "die Musik", en: "music" },
  { id: "en6_0032", de: "der Fernseher", en: "TV", alt: ["television"] },
  { id: "en6_0033", de: "auch", en: "too" },
  { id: "en6_0034", de: "tanzen", en: "dance" },
  { id: "en6_0035", de: "spielen", en: "play" },
  { id: "en6_0036", de: "das Spiel", en: "game" },
  { id: "en6_0037", de: "lesen", en: "read" },
  { id: "en6_0038", de: "das Buch", en: "book" },
  { id: "en6_0039", de: "reiten", en: "ride" },
  { id: "en6_0040", de: "schwimmen", en: "swim" },
  { id: "en6_0041", de: "das Tier", en: "animal" },
  { id: "en6_0042", de: "haben", en: "have" },
  { id: "en6_0043", de: "das Pony", en: "pony" },
  { id: "en6_0044", de: "lieben", en: "love" },
  { id: "en6_0045", de: "die Katze", en: "cat" },
  { id: "en6_0046", de: "der Bär", en: "bear" },
  { id: "en6_0047", de: "die Ratte", en: "rat" },
  { id: "en6_0048", de: "der Affe", en: "monkey" },
  { id: "en6_0049", de: "der Vogel", en: "bird" },
  { id: "en6_0050", de: "die Schlange", en: "snake" },
  { id: "en6_0051", de: "der Hund", en: "dog" },
  { id: "en6_0052", de: "das Krokodil", en: "crocodile" },
  { id: "en6_0053", de: "das Kaninchen", en: "rabbit" },
  { id: "en6_0054", de: "der Hamster", en: "hamster" },
  { id: "en6_0055", de: "der Fisch", en: "fish" },
  { id: "en6_0056", de: "der Tiger", en: "tiger" },
  { id: "en6_0057", de: "der Elefant", en: "elephant" },
  { id: "en6_0058", de: "das Haustier", en: "pet" },
  { id: "en6_0059", de: "wild", en: "wild" },
  { id: "en6_0060", de: "das Paar", en: "pair" },
  { id: "en6_0061", de: "das Ding / die Sache", en: "thing" },
  { id: "en6_0062", de: "sich erinnern (an)", en: "remember" },
  { id: "en6_0063", de: "gehen / fahren", en: "go" },
  { id: "en6_0064", de: "der Park", en: "park" },
  { id: "en6_0065", de: "das Fahrrad", en: "bike" },
  { id: "en6_0066", de: "großartig / prima", en: "great" },
  { id: "en6_0067", de: "klein", en: "small" },
  { id: "en6_0068", de: "groß", en: "big" },
  { id: "en6_0069", de: "alt", en: "old" },
  { id: "en6_0070", de: "neu", en: "new" },
  { id: "en6_0071", de: "cool", en: "cool" },
  { id: "en6_0072", de: "die Ferien", en: "holidays" },
  { id: "en6_0073", de: "die Geschichte", en: "story" },
  { id: "en6_0074", de: "Hallo", en: "hello", alt: ["hi"] },
  { id: "en6_0075", de: "nein", en: "no" },
  { id: "en6_0076", de: "weg / fort", en: "away" },
  { id: "en6_0077", de: "dumm / blöd", en: "stupid" },
  { id: "en6_0078", de: "die Möwe", en: "seagull" },
  { id: "en6_0079", de: "helfen / die Hilfe", en: "help" },
  { id: "en6_0080", de: "die Schule", en: "school" },
  { id: "en6_0081", de: "das Geräusch / der Klang", en: "sound" },
  { id: "en6_0082", de: "der Junge", en: "boy" },
  { id: "en6_0083", de: "das Mädchen", en: "girl" },
  { id: "en6_0084", de: "der/die Lehrer/in", en: "teacher" },
  { id: "en6_0085", de: "das Auto", en: "car" },
  { id: "en6_0086", de: "das Handy / Mobiltelefon", en: "mobile", alt: ["mobile phone"] },
  { id: "en6_0087", de: "der Morgen", en: "morning" },
  { id: "en6_0088", de: "gut", en: "good" },
  { id: "en6_0089", de: "der Bruder", en: "brother" },
  { id: "en6_0090", de: "die Schwester", en: "sister" },
  { id: "en6_0091", de: "der/die Freund/in", en: "friend" },
  { id: "en6_0092", de: "das Dorf", en: "village" },
  { id: "en6_0093", de: "nahe / in der Nähe", en: "near" },
  { id: "en6_0094", de: "das Alter", en: "age" },
  { id: "en6_0095", de: "der Raum / das Zimmer", en: "room" },
  { id: "en6_0096", de: "die Kantine / Mensa", en: "canteen" },
  { id: "en6_0097", de: "die Kunst", en: "art" },
  { id: "en6_0098", de: "die Naturwissenschaft", en: "science" },
  { id: "en6_0099", de: "das Labor", en: "lab" },
  { id: "en6_0100", de: "die Sporthalle", en: "sports hall" },
  { id: "en6_0101", de: "der Schulsport", en: "PE" },
  { id: "en6_0102", de: "die (Unterrichts-)Stunde", en: "lesson" },
  { id: "en6_0103", de: "nun / jetzt", en: "now" },
  { id: "en6_0104", de: "wo?", en: "where" },
  { id: "en6_0105", de: "hier", en: "here" },
  { id: "en6_0106", de: "der Stundenplan", en: "timetable" },
  { id: "en6_0107", de: "die Zeit / Uhrzeit", en: "time" },
  { id: "en6_0108", de: "der Montag", en: "Monday" },
  { id: "en6_0109", de: "der Dienstag", en: "Tuesday" },
  { id: "en6_0110", de: "der Mittwoch", en: "Wednesday" },
  { id: "en6_0111", de: "der Donnerstag", en: "Thursday" },
  { id: "en6_0112", de: "der Freitag", en: "Friday" },
  { id: "en6_0113", de: "die Schulversammlung", en: "assembly" },
  { id: "en6_0114", de: "die Technik / Technologie", en: "technology" },
  { id: "en6_0115", de: "die Erdkunde / Geografie", en: "geography" },
  { id: "en6_0116", de: "die Mathematik", en: "maths", alt: ["math"] },
  { id: "en6_0117", de: "die Geschichte (Fach)", en: "history" },
  { id: "en6_0118", de: "Französisch", en: "French" },
  { id: "en6_0119", de: "die Pause", en: "break" },
  { id: "en6_0120", de: "das Mittagessen", en: "lunch" },
  { id: "en6_0121", de: "das Schauspiel", en: "drama" },
  { id: "en6_0122", de: "jeder Tag", en: "every day" },
  { id: "en6_0123", de: "richtig", en: "right" },
  { id: "en6_0124", de: "falsch", en: "wrong" },
  { id: "en6_0125", de: "die (Groß-)Stadt", en: "city" },
  { id: "en6_0126", de: "anfangen / beginnen", en: "start" },
  { id: "en6_0127", de: "mit", en: "with" },
  { id: "en6_0128", de: "das Klassenzimmer", en: "classroom" },
  { id: "en6_0129", de: "ja", en: "yes" },
  { id: "en6_0130", de: "aber", en: "but" },
  { id: "en6_0131", de: "alle", en: "all" },
  { id: "en6_0132", de: "die Leute / Menschen", en: "people" },
  { id: "en6_0133", de: "der Ort / Platz", en: "place" },
  { id: "en6_0134", de: "machen / herstellen", en: "make" },
  { id: "en6_0135", de: "für", en: "for" },
  { id: "en6_0136", de: "der Blazer", en: "blazer" },
  { id: "en6_0137", de: "der Pullover", en: "pullover" },
  { id: "en6_0138", de: "das Hemd", en: "shirt" },
  { id: "en6_0139", de: "der Schuh", en: "shoe" },
  { id: "en6_0140", de: "der Rock", en: "skirt" },
  { id: "en6_0141", de: "die Socke", en: "sock" },
  { id: "en6_0142", de: "die Krawatte", en: "tie" },
  { id: "en6_0143", de: "die Strumpfhose", en: "tights" },
  { id: "en6_0144", de: "die Hose", en: "trousers" },
  { id: "en6_0145", de: "die Uniform", en: "uniform" },
  { id: "en6_0146", de: "wichtig", en: "important" },
  { id: "en6_0147", de: "der/die Schulleiter/in", en: "principal" },
  { id: "en6_0148", de: "hoffen", en: "hope" },
  { id: "en6_0149", de: "froh / glücklich", en: "happy" },
  { id: "en6_0150", de: "bitte", en: "please" },
  { id: "en6_0151", de: "Tut mir leid", en: "sorry" },
  { id: "en6_0152", de: "daheim / zu Hause", en: "at home" },
  { id: "en6_0153", de: "das Zuhause", en: "home" },
  { id: "en6_0154", de: "die Hausaufgabe", en: "homework" },
  { id: "en6_0155", de: "schreiben", en: "write" },
  { id: "en6_0156", de: "wissen / kennen", en: "know" },
  { id: "en6_0157", de: "schlecht / schlimm", en: "bad" },
  { id: "en6_0158", de: "die Idee", en: "idea" },
  { id: "en6_0159", de: "brauchen / benötigen", en: "need" },
  { id: "en6_0160", de: "das Papier", en: "paper" },
  { id: "en6_0161", de: "die Schere", en: "scissors" },
  { id: "en6_0162", de: "sagen", en: "say" },
  { id: "en6_0163", de: "denken / meinen", en: "think" },
  { id: "en6_0164", de: "das Theater", en: "theatre", alt: ["theater"] },
  { id: "en6_0165", de: "die Broschüre", en: "brochure" },
  { id: "en6_0166", de: "zurück", en: "back" },
  { id: "en6_0167", de: "das Pfund", en: "pound" },
  { id: "en6_0168", de: "der Bleistiftanspitzer", en: "pencil sharpener" },
  { id: "en6_0169", de: "der Radiergummi", en: "rubber" },
  { id: "en6_0170", de: "das Lineal", en: "ruler" },
  { id: "en6_0171", de: "der Stift / Kugelschreiber", en: "pen" },
  { id: "en6_0172", de: "der Bleistift", en: "pencil" },
  { id: "en6_0173", de: "das Federmäppchen", en: "pencil case" },
  { id: "en6_0174", de: "der Taschenrechner", en: "calculator" },
  { id: "en6_0175", de: "das Übungsheft", en: "exercise book" },
  { id: "en6_0176", de: "die Übung / Aufgabe", en: "exercise" },
  { id: "en6_0177", de: "das Tagebuch", en: "diary" },
  { id: "en6_0178", de: "der Locher", en: "hole punch" },
  { id: "en6_0179", de: "kaufen", en: "buy" },
  { id: "en6_0180", de: "das Kind", en: "child" },
  { id: "en6_0181", de: "das Netz", en: "network" },
  { id: "en6_0182", de: "der Samstag", en: "Saturday" },
  { id: "en6_0183", de: "der Sonntag", en: "Sunday" },
  { id: "en6_0184", de: "das Wochenende", en: "weekend" },
  { id: "en6_0185", de: "die Schultasche", en: "school bag" },
  { id: "en6_0186", de: "der Ausdruck / die Wendung", en: "phrase" },
  { id: "en6_0187", de: "die Karte", en: "card" },
  { id: "en6_0188", de: "der Kasten / die Kiste", en: "box" },
  { id: "en6_0189", de: "auf Englisch", en: "in English" },
  { id: "en6_0190", de: "sprechen / reden", en: "talk" },
  { id: "en6_0191", de: "(aus)leihen", en: "borrow" },
  { id: "en6_0192", de: "nächste/r", en: "next" },
  { id: "en6_0193", de: "sicher", en: "sure" },
  { id: "en6_0194", de: "Deutsch", en: "German" },
  { id: "en6_0195", de: "buchstabieren", en: "spell" },
  { id: "en6_0196", de: "das Alphabet", en: "alphabet" },
  { id: "en6_0197", de: "die Adresse", en: "address" },
  { id: "en6_0198", de: "die Telefonnummer", en: "phone number" },
  { id: "en6_0199", de: "die Nummer", en: "number" },
  { id: "en6_0200", de: "die Straße (in Orten)", en: "street" },
  { id: "en6_0201", de: "die Straße / Landstraße", en: "road" },
  { id: "en6_0202", de: "das Foto", en: "photo" },
  { id: "en6_0203", de: "das Haus", en: "house" },
  { id: "en6_0204", de: "die Wohnung", en: "flat" },
  { id: "en6_0205", de: "die Küche", en: "kitchen" },
  { id: "en6_0206", de: "das Schlafzimmer", en: "bedroom" },
  { id: "en6_0207", de: "der Garten", en: "garden" },
  { id: "en6_0208", de: "das Wohnzimmer", en: "living room" },
  { id: "en6_0209", de: "Mama / Mutti", en: "mum" },
  { id: "en6_0210", de: "die Mutter", en: "mother" },
  { id: "en6_0211", de: "Papa / Vati", en: "dad" },
  { id: "en6_0212", de: "der Vater", en: "father" },
  { id: "en6_0213", de: "leben / wohnen", en: "live" },
  { id: "en6_0214", de: "der Flur / die Diele", en: "hall" },
  { id: "en6_0215", de: "die Toilette", en: "toilet" },
  { id: "en6_0216", de: "das Badezimmer", en: "bathroom" },
  { id: "en6_0217", de: "die Garage", en: "garage" },
  { id: "en6_0218", de: "der Traum", en: "dream" },
  { id: "en6_0219", de: "die Familie", en: "family" },
  { id: "en6_0220", de: "oben", en: "upstairs" },
  { id: "en6_0221", de: "unten", en: "downstairs" },
  { id: "en6_0222", de: "immer", en: "always" },
  { id: "en6_0223", de: "der Platz / Raum", en: "space" },
  { id: "en6_0224", de: "der Stiefvater", en: "stepdad", alt: ["stepfather"] },
  { id: "en6_0225", de: "die Stiefmutter", en: "stepmum", alt: ["stepmother"] },
  { id: "en6_0226", de: "die Stiefschwester", en: "stepsister" },
  { id: "en6_0227", de: "der Stiefbruder", en: "stepbrother" },
  { id: "en6_0228", de: "vermissen", en: "miss" },
  { id: "en6_0229", de: "echt / wirklich", en: "real" },
  { id: "en6_0230", de: "der/die Partner/in", en: "partner" },
  { id: "en6_0231", de: "süß / niedlich", en: "cute" },
  { id: "en6_0232", de: "der Stammbaum", en: "family tree" },
  { id: "en6_0233", de: "der Baum", en: "tree" },
  { id: "en6_0234", de: "zusammen", en: "together" },
  { id: "en6_0235", de: "der/die Cousin/e", en: "cousin" },
  { id: "en6_0236", de: "die Tante", en: "aunt" },
  { id: "en6_0237", de: "der Onkel", en: "uncle" },
  { id: "en6_0238", de: "die Eltern", en: "parents" },
  { id: "en6_0239", de: "die Großeltern", en: "grandparents" },
  { id: "en6_0240", de: "der Großvater", en: "grandfather" },
  { id: "en6_0241", de: "die Großmutter", en: "grandmother" },
  { id: "en6_0242", de: "das Problem", en: "problem" },
  { id: "en6_0243", de: "unordentlich", en: "messy" },
  { id: "en6_0244", de: "rechthaberisch / herrisch", en: "bossy" },
  { id: "en6_0245", de: "tun / machen", en: "do" },
  { id: "en6_0246", de: "laut", en: "noisy" },
  { id: "en6_0247", de: "der Teppich / Läufer", en: "rug" },
  { id: "en6_0248", de: "der Stuhl", en: "chair" },
  { id: "en6_0249", de: "der Schreibtisch", en: "desk" },
  { id: "en6_0250", de: "das Regal", en: "shelf" },
  { id: "en6_0251", de: "die Lampe", en: "lamp" },
  { id: "en6_0252", de: "der Tisch", en: "table" },
  { id: "en6_0253", de: "das Bett", en: "bed" },
  { id: "en6_0254", de: "das Kissen", en: "cushion" },
  { id: "en6_0255", de: "der Spiegel", en: "mirror" },
  { id: "en6_0256", de: "der Kleiderschrank", en: "wardrobe" },
  { id: "en6_0257", de: "verschieden / anders", en: "different" },
  { id: "en6_0258", de: "die Überraschung", en: "surprise" },
  { id: "en6_0259", de: "müde", en: "tired" },
  { id: "en6_0260", de: "wirklich", en: "really" },
  { id: "en6_0261", de: "streng", en: "strict" },
  { id: "en6_0262", de: "fies / gemein", en: "mean" },
  { id: "en6_0263", de: "zuhören", en: "listen" },
  { id: "en6_0264", de: "die Frage", en: "question" },
  { id: "en6_0265", de: "die Antwort", en: "answer" },
  { id: "en6_0266", de: "einfach / leicht", en: "easy" },
  { id: "en6_0267", de: "schwierig / schwer", en: "difficult" },
  { id: "en6_0268", de: "das Beispiel", en: "example" },
  { id: "en6_0269", de: "die Nachrichten", en: "news" },
  { id: "en6_0270", de: "das Kino", en: "cinema" },
  { id: "en6_0271", de: "anschauen / beobachten", en: "watch" },
  { id: "en6_0272", de: "die Sendung", en: "programme", alt: ["program"] },
  { id: "en6_0273", de: "bald", en: "soon" },
  { id: "en6_0274", de: "das Restaurant", en: "restaurant" },
  { id: "en6_0275", de: "wieder / noch einmal", en: "again" },
  { id: "en6_0276", de: "die Stadt", en: "town" },
  { id: "en6_0277", de: "einsam", en: "lonely" },
  { id: "en6_0278", de: "der Text / die SMS", en: "text" },
  { id: "en6_0279", de: "die Woche", en: "week" },
  { id: "en6_0280", de: "viele / viel", en: "lots" },
  { id: "en6_0281", de: "weil", en: "because" },
  { id: "en6_0282", de: "das Meer", en: "sea" },
  { id: "en6_0283", de: "arbeiten", en: "work" },
  { id: "en6_0284", de: "zumachen / schließen", en: "close" },
  { id: "en6_0285", de: "die Tür", en: "door" },
  { id: "en6_0286", de: "die Seite", en: "page" },
  { id: "en6_0287", de: "oft", en: "often" },
  { id: "en6_0288", de: "der Sommer", en: "summer" },
  { id: "en6_0289", de: "die Feuerwache", en: "fire station" },
  { id: "en6_0290", de: "der Nachname / Familienname", en: "family name" },
  { id: "en6_0291", de: "nie / niemals", en: "never" },
  { id: "en6_0292", de: "das Aquarium", en: "aquarium" },
  { id: "en6_0293", de: "der Markt", en: "market" },
  { id: "en6_0294", de: "das Einkaufszentrum", en: "shopping centre", alt: ["shopping center"] },
  { id: "en6_0295", de: "bleiben", en: "stay" },
  { id: "en6_0296", de: "das Frühstück", en: "breakfast" },
  { id: "en6_0297", de: "jeder / alle", en: "everybody" },
  { id: "en6_0298", de: "zuerst", en: "first" },
  { id: "en6_0299", de: "danach / dann", en: "then" },
  { id: "en6_0300", de: "das Gemüse", en: "vegetables" },
  { id: "en6_0301", de: "langweilig", en: "boring" },
  { id: "en6_0302", de: "die Süßigkeiten", en: "sweets" },
  { id: "en6_0303", de: "der Nachmittag", en: "afternoon" },
  { id: "en6_0304", de: "meistens / normalerweise", en: "usually" },
  { id: "en6_0305", de: "da / dort", en: "there" },
  { id: "en6_0306", de: "der Abend", en: "evening" },
  { id: "en6_0307", de: "manchmal", en: "sometimes" },
  { id: "en6_0308", de: "kommen", en: "come" },
  { id: "en6_0309", de: "das Geschenk", en: "present" },
  { id: "en6_0310", de: "heute", en: "today" },
  { id: "en6_0311", de: "die Turnschuhe", en: "trainers" },
  { id: "en6_0312", de: "teuer", en: "expensive" },
  { id: "en6_0313", de: "der Kapuzenpullover", en: "hoodie" },
  { id: "en6_0314", de: "hassen", en: "hate" },
  { id: "en6_0315", de: "schrecklich / fürchterlich", en: "terrible" },
  { id: "en6_0316", de: "der Monat", en: "month" },
  { id: "en6_0317", de: "Januar", en: "January" },
  { id: "en6_0318", de: "Februar", en: "February" },
  { id: "en6_0319", de: "März", en: "March" },
  { id: "en6_0320", de: "April", en: "April" },
  { id: "en6_0321", de: "Mai", en: "May" },
  { id: "en6_0322", de: "Juni", en: "June" },
  { id: "en6_0323", de: "Juli", en: "July" },
  { id: "en6_0324", de: "August", en: "August" },
  { id: "en6_0325", de: "September", en: "September" },
  { id: "en6_0326", de: "Oktober", en: "October" },
  { id: "en6_0327", de: "November", en: "November" },
  { id: "en6_0328", de: "Dezember", en: "December" },
  { id: "en6_0329", de: "das Datum", en: "date" },
  { id: "en6_0330", de: "wann?", en: "when" },
  { id: "en6_0331", de: "frei", en: "free" },
  { id: "en6_0332", de: "aufstehen", en: "get up" },
  { id: "en6_0333", de: "früh", en: "early" },
  { id: "en6_0334", de: "faul", en: "lazy" },
  { id: "en6_0335", de: "spät", en: "late" },
  { id: "en6_0336", de: "nachts / in der Nacht", en: "at night" },
  { id: "en6_0337", de: "(zu Fuß) gehen", en: "walk" },
  { id: "en6_0338", de: "unglücklich", en: "unhappy" },
  { id: "en6_0339", de: "planen", en: "plan" },
  { id: "en6_0340", de: "etwas", en: "something" },
  { id: "en6_0341", de: "das Konzert", en: "concert" },
  { id: "en6_0342", de: "der Zoo", en: "zoo" },
  { id: "en6_0343", de: "aufgeregt / gespannt", en: "excited" },
  { id: "en6_0344", de: "der Hügel", en: "hill" },
  { id: "en6_0345", de: "schnell", en: "fast" },
  { id: "en6_0346", de: "das Bein", en: "leg" },
  { id: "en6_0347", de: "fallen / hinfallen", en: "fall" },
  { id: "en6_0348", de: "das Krankenhaus", en: "hospital" },
  { id: "en6_0349", de: "oder", en: "or" },
  { id: "en6_0350", de: "das Ende", en: "end" },
  { id: "en6_0351", de: "der (Schluss-)Verkauf", en: "sale" },
  { id: "en6_0352", de: "britisch", en: "British" },
  { id: "en6_0353", de: "das Geld", en: "money" },
  { id: "en6_0354", de: "der Mann", en: "man" },
  { id: "en6_0355", de: "das Sonderangebot", en: "special offer" },
  { id: "en6_0356", de: "besondere/r", en: "special" },
  { id: "en6_0357", de: "derselbe / dieselbe", en: "the same" },
  { id: "en6_0358", de: "probieren / ausprobieren", en: "try" },
  { id: "en6_0359", de: "der Helm", en: "helmet" },
  { id: "en6_0360", de: "die Anzeige / Werbung", en: "advert" },
  { id: "en6_0361", de: "raten / erraten", en: "guess" },
  { id: "en6_0362", de: "die Welt", en: "world" },
  { id: "en6_0363", de: "der/die Besucher/in", en: "visitor" },
  { id: "en6_0364", de: "der Stall / die Scheune", en: "barn" },
  { id: "en6_0365", de: "streicheln", en: "stroke" },
  { id: "en6_0366", de: "der Esel", en: "donkey" },
  { id: "en6_0367", de: "die Ente", en: "duck" },
  { id: "en6_0368", de: "der Teich", en: "pond" },
  { id: "en6_0369", de: "das Feld / die Weide", en: "field" },
  { id: "en6_0370", de: "die Kuh", en: "cow" },
  { id: "en6_0371", de: "das Schwein", en: "pig" },
  { id: "en6_0372", de: "das Schaf", en: "sheep" },
  { id: "en6_0373", de: "das Huhn / Hähnchen", en: "chicken" },
  { id: "en6_0374", de: "das Leben", en: "life" },
  { id: "en6_0375", de: "der Wecker", en: "alarm clock" },
  { id: "en6_0376", de: "wecken", en: "wake" },
  { id: "en6_0377", de: "andere/r", en: "other" },
  { id: "en6_0378", de: "draußen", en: "outside" },
  { id: "en6_0379", de: "drinnen", en: "inside" },
  { id: "en6_0380", de: "füttern", en: "feed" },
  { id: "en6_0381", de: "sich fertig machen", en: "get ready" },
  { id: "en6_0382", de: "essen / fressen", en: "eat" },
  { id: "en6_0383", de: "ungefähr", en: "about" },
  { id: "en6_0384", de: "sich kümmern um", en: "look after" },
  { id: "en6_0385", de: "Sport treiben", en: "do sport" },
  { id: "en6_0386", de: "nichts", en: "nothing" },
  { id: "en6_0387", de: "sitzen", en: "sit" },
  { id: "en6_0388", de: "das Jahr", en: "year" },
  { id: "en6_0389", de: "der Dialog", en: "dialogue" },
  { id: "en6_0390", de: "das Gefühl", en: "feeling" },
  { id: "en6_0391", de: "die Diskussion", en: "discussion" },
  { id: "en6_0392", de: "sich fühlen", en: "feel" },
  { id: "en6_0393", de: "ein bisschen", en: "a bit" },
  { id: "en6_0394", de: "der Rollstuhl", en: "wheelchair" },
  { id: "en6_0395", de: "normal / gewöhnlich", en: "normal" },
  { id: "en6_0396", de: "gewinnen", en: "win" },
  { id: "en6_0397", de: "fragen", en: "ask" },
  { id: "en6_0398", de: "das Getränk / trinken", en: "drink" },
  { id: "en6_0399", de: "verstehen", en: "understand" },
  { id: "en6_0400", de: "sprechen", en: "speak" },
  { id: "en6_0401", de: "der Mund", en: "mouth" },
  { id: "en6_0402", de: "flauschig / pelzig", en: "furry" },
  { id: "en6_0403", de: "interessant", en: "interesting" },
  { id: "en6_0404", de: "der Käfig", en: "cage" },
  { id: "en6_0405", de: "warum?", en: "why" },
  { id: "en6_0406", de: "freundlich", en: "friendly" },
  { id: "en6_0407", de: "die Schulter", en: "shoulder" },
  { id: "en6_0408", de: "das Obst", en: "fruit" },
  { id: "en6_0409", de: "die Nuss", en: "nut" },
  { id: "en6_0410", de: "schlafen", en: "sleep" },
  { id: "en6_0411", de: "finden", en: "find" },
  { id: "en6_0412", de: "der Bus", en: "bus" },
  { id: "en6_0413", de: "nervös / aufgeregt", en: "nervous" },
  { id: "en6_0414", de: "das Abenteuer", en: "adventure" },
  { id: "en6_0415", de: "das Land", en: "country" },
  { id: "en6_0416", de: "die Szene", en: "scene" },
  { id: "en6_0417", de: "einladen", en: "invite" },
  { id: "en6_0418", de: "die Schlafparty", en: "sleepover" },
  { id: "en6_0419", de: "bringen / mitbringen", en: "bring" },
  { id: "en6_0420", de: "der Schlafsack", en: "sleeping bag" },
  { id: "en6_0421", de: "nass", en: "wet" },
  { id: "en6_0422", de: "lachen", en: "laugh" },
  { id: "en6_0423", de: "durch", en: "through" },
  { id: "en6_0424", de: "hungrig sein", en: "be hungry" },
  { id: "en6_0425", de: "gefährlich", en: "dangerous" },
  { id: "en6_0426", de: "der Lärm", en: "noise" },
  { id: "en6_0427", de: "nur / bloß", en: "only" },
  { id: "en6_0428", de: "das Zeichen / Schild", en: "sign" },
  { id: "en6_0429", de: "links", en: "left" },
  { id: "en6_0430", de: "rechts", en: "right" },
  { id: "en6_0431", de: "die Einladung", en: "invitation" },
  { id: "en6_0432", de: "das Picknick", en: "picnic" },
  { id: "en6_0433", de: "benutzen / verwenden", en: "use" },
  { id: "en6_0434", de: "das Wörterbuch", en: "dictionary" },
  { id: "en6_0435", de: "das Gedicht", en: "poem" },
  { id: "en6_0436", de: "der Hafen", en: "harbour", alt: ["harbor"] },
  { id: "en6_0437", de: "das Café", en: "cafe" },
  { id: "en6_0438", de: "die Fähre", en: "ferry" },
  { id: "en6_0439", de: "die Pommes frites", en: "chips" },
  { id: "en6_0440", de: "der Salat", en: "salad" },
  { id: "en6_0441", de: "die Suppe", en: "soup" },
  { id: "en6_0442", de: "die Flasche", en: "bottle" },
  { id: "en6_0443", de: "das Wasser", en: "water" },
  { id: "en6_0444", de: "die Tasse", en: "cup" },
  { id: "en6_0445", de: "der Kaffee", en: "coffee" },
  { id: "en6_0446", de: "der Tee", en: "tea" },
  { id: "en6_0447", de: "klingeln / läuten", en: "ring" },
  { id: "en6_0448", de: "der Job / die Stelle", en: "job" },
  { id: "en6_0449", de: "beschäftigt sein", en: "be busy" },
  { id: "en6_0450", de: "kochen", en: "cook" },
  { id: "en6_0451", de: "abwaschen", en: "wash up" },
  { id: "en6_0452", de: "müssen", en: "must" },
  { id: "en6_0453", de: "hart arbeiten", en: "work hard" },
  { id: "en6_0454", de: "der Brief", en: "letter" },
  { id: "en6_0455", de: "besorgt / beunruhigt", en: "worried" },
  { id: "en6_0456", de: "im Moment", en: "at the moment" },
  { id: "en6_0457", de: "anrufen", en: "phone" },
  { id: "en6_0458", de: "geschehen / passieren", en: "happen" },
  { id: "en6_0459", de: "einen Kopfsprung machen", en: "dive" },
  { id: "en6_0460", de: "verstecken", en: "hide" },
  { id: "en6_0461", de: "schicken / senden", en: "send" },
  { id: "en6_0462", de: "die Gitarre", en: "guitar" },
  { id: "en6_0463", de: "lernen", en: "learn" },
  { id: "en6_0464", de: "das Schlagzeug", en: "drums" },
  { id: "en6_0465", de: "die Gruppe", en: "group" },
  { id: "en6_0466", de: "das Instrument", en: "instrument" },
  { id: "en6_0467", de: "jung", en: "young" },
  { id: "en6_0468", de: "der/die Musiker/in", en: "musician" },
  { id: "en6_0469", de: "der/die Sänger/in", en: "singer" },
  { id: "en6_0470", de: "singen", en: "sing" },
  { id: "en6_0471", de: "das Klavier", en: "piano" },
  { id: "en6_0472", de: "den Tisch decken", en: "set the table" },
  { id: "en6_0473", de: "sauber machen / putzen", en: "clean" },
  { id: "en6_0474", de: "klein (winzig)", en: "little" },
  { id: "en6_0475", de: "vielleicht", en: "maybe" },
  { id: "en6_0476", de: "der/die Koch/Köchin", en: "cook" },
  { id: "en6_0477", de: "die Form", en: "form" },
  { id: "en6_0478", de: "das Essen / Lebensmittel", en: "food" },
  { id: "en6_0479", de: "das Fenster", en: "window" },
  { id: "en6_0480", de: "hören", en: "hear" },
  { id: "en6_0481", de: "der Unterschied", en: "difference" },
  { id: "en6_0482", de: "einige / ein paar", en: "some" },
  { id: "en6_0483", de: "der (Sitz-)Platz", en: "seat" },
  { id: "en6_0484", de: "das Gesicht", en: "face" },
  { id: "en6_0485", de: "die (feste) Freundin", en: "girlfriend" },
  { id: "en6_0486", de: "der (feste) Freund", en: "boyfriend" },
  { id: "en6_0487", de: "schwer / hart", en: "hard" },
  { id: "en6_0488", de: "stolz (auf)", en: "proud" },
  { id: "en6_0489", de: "wahr", en: "true" },
  { id: "en6_0490", de: "falsch (nicht wahr)", en: "false" },
  { id: "en6_0491", de: "beschreiben", en: "describe" },
  { id: "en6_0492", de: "neben", en: "next to" },
  { id: "en6_0493", de: "zwischen", en: "between" },
  { id: "en6_0494", de: "hinter", en: "behind" },
  { id: "en6_0495", de: "unter", en: "under" },
  { id: "en6_0496", de: "vor", en: "in front of" },
  { id: "en6_0497", de: "der Apfel", en: "apple" },
  { id: "en6_0498", de: "das Rezept", en: "recipe" },
  { id: "en6_0499", de: "die Marmelade", en: "jam" },
  { id: "en6_0500", de: "die Sahne", en: "cream" },
  { id: "en6_0501", de: "das Paddelboot / Kanu", en: "canoe" },
  { id: "en6_0502", de: "der Themenpark", en: "theme park" },
  { id: "en6_0503", de: "der Badeanzug", en: "swimsuit" },
  { id: "en6_0504", de: "die Badehose", en: "swimming trunks" },
  { id: "en6_0505", de: "das Handtuch", en: "towel" },
  { id: "en6_0506", de: "die Sonnenbrille", en: "sunglasses" },
  { id: "en6_0507", de: "der Hut", en: "hat" },
  { id: "en6_0508", de: "die (Kartoffel-)Chips", en: "crisps" },
  { id: "en6_0509", de: "das Würstchen / die Wurst", en: "sausage" },
  { id: "en6_0510", de: "die Apfelsine", en: "orange" },
  { id: "en6_0511", de: "die Schokolade", en: "chocolate" },
  { id: "en6_0512", de: "der Keks", en: "biscuit" },
  { id: "en6_0513", de: "der Lautsprecher", en: "speaker" },
  { id: "en6_0514", de: "der Schwimmreifen", en: "tube" },
  { id: "en6_0515", de: "der (Regen-)Schirm", en: "umbrella" },
  { id: "en6_0516", de: "die Sonnencreme", en: "suncream" },
  { id: "en6_0517", de: "die Decke", en: "blanket" },
  { id: "en6_0518", de: "vergessen", en: "forget" },
  { id: "en6_0519", de: "die Kette", en: "chain" },
  { id: "en6_0520", de: "an Bord", en: "aboard" },
  { id: "en6_0521", de: "die Flaschenpost", en: "message in a bottle" },
  { id: "en6_0522", de: "die Frau", en: "woman" },
  { id: "en6_0523", de: "der/die Schmuggler/in", en: "smuggler" },
  { id: "en6_0524", de: "tun / legen / stellen", en: "put" },
  { id: "en6_0525", de: "besser", en: "better" },
  { id: "en6_0526", de: "die Minute", en: "minute" },
  { id: "en6_0527", de: "sich beeilen", en: "hurry" },
  { id: "en6_0528", de: "der Platz (in der Stadt)", en: "square" },
  { id: "en6_0529", de: "der Stadtplan / die Landkarte", en: "map" },
  { id: "en6_0530", de: "noch ein/e", en: "another" },
  { id: "en6_0531", de: "folgen / verfolgen", en: "follow" },
  { id: "en6_0532", de: "schieben", en: "push" },
  { id: "en6_0533", de: "die Uhr", en: "clock" },
  { id: "en6_0534", de: "schnell (rasch)", en: "quick" },
  { id: "en6_0535", de: "langsam", en: "slow" },
  { id: "en6_0536", de: "heiß", en: "hot" },
  { id: "en6_0537", de: "das Eis", en: "ice cream" },
  { id: "en6_0538", de: "warten (auf)", en: "wait" },
  { id: "en6_0539", de: "die Tochter", en: "daughter" },
  { id: "en6_0540", de: "herauskommen", en: "get out" },
  { id: "en6_0541", de: "unheimlich", en: "scary" },
  { id: "en6_0542", de: "fliegen", en: "fly" },
  { id: "en6_0543", de: "der Berg", en: "mountain" },
  { id: "en6_0544", de: "der See", en: "lake" },
  { id: "en6_0545", de: "das Grillfest", en: "barbecue", alt: ["barbeque"] },
  { id: "en6_0546", de: "umhergehen", en: "walk around" },
  { id: "en6_0547", de: "das Wetter", en: "weather" },
  { id: "en6_0548", de: "warm", en: "warm" },
  { id: "en6_0549", de: "kalt", en: "cold" },
  { id: "en6_0550", de: "sonnig", en: "sunny" },
  { id: "en6_0551", de: "die Sonne", en: "sun" },
  { id: "en6_0552", de: "regnerisch", en: "rainy" },
  { id: "en6_0553", de: "der Regen", en: "rain" },
  { id: "en6_0554", de: "schön", en: "beautiful" },
  { id: "en6_0555", de: "diese", en: "these" },
  { id: "en6_0556", de: "morgen", en: "tomorrow" },
  { id: "en6_0557", de: "geben", en: "give" },
  { id: "en6_0558", de: "gehen", en: "go" },
  { id: "en6_0559", de: "komisch", en: "funny" },
  { id: "en6_0560", de: "arm", en: "poor" },
  { id: "en6_0561", de: "gestern", en: "yesterday" },
  { id: "en6_0562", de: "der Unterricht", en: "class" },
  { id: "en6_0563", de: "treffen", en: "meet" },
  { id: "en6_0564", de: "bekommen", en: "get" },
  { id: "en6_0565", de: "ziemlich", en: "quite" },
  { id: "en6_0566", de: "allein", en: "alone" },
  { id: "en6_0567", de: "lang", en: "long" },
  { id: "en6_0568", de: "kurz", en: "short" },
  { id: "en6_0569", de: "das Mitteilungsblatt", en: "newsletter" },
  { id: "en6_0570", de: "die Mittagszeit", en: "lunchtime" },
  { id: "en6_0571", de: "fit", en: "fit" },
  { id: "en6_0572", de: "das Experiment", en: "experiment" },
  { id: "en6_0573", de: "schauspielern", en: "act" },
  { id: "en6_0574", de: "machen", en: "do" },
  { id: "en6_0575", de: "Weihnachten", en: "Christmas" },
  { id: "en6_0576", de: "das Theaterstück", en: "play" },
  { id: "en6_0577", de: "gesund", en: "healthy" },
  { id: "en6_0578", de: "lecker", en: "yummy", alt: ["delicious"] },
  { id: "en6_0579", de: "der Ausflug", en: "trip" },
  { id: "en6_0580", de: "das Projekt", en: "project" },
  { id: "en6_0581", de: "herausfinden", en: "find out" },
  { id: "en6_0582", de: "der Kreis", en: "circle" },
  { id: "en6_0583", de: "der Kanal", en: "channel" },
  { id: "en6_0584", de: "fahren", en: "drive" },
  { id: "en6_0585", de: "Freunde finden", en: "make friends" },
  { id: "en6_0586", de: "die Gegenwart", en: "present" },
  { id: "en6_0587", de: "die Vergangenheit", en: "past" },
  { id: "en6_0588", de: "fühlen", en: "feel" },
  { id: "en6_0589", de: "die Regel", en: "rule" },
  { id: "en6_0590", de: "der Satz", en: "sentence" },
  { id: "en6_0591", de: "suchen", en: "look for" },
  { id: "en6_0592", de: "schließlich", en: "in the end" },
  { id: "en6_0593", de: "der Gewinner", en: "winner" },
  { id: "en6_0594", de: "jeder", en: "each" },
  { id: "en6_0595", de: "beenden", en: "finish" },
  { id: "en6_0596", de: "trinken", en: "drink" },
  { id: "en6_0597", de: "essen", en: "eat" },
  { id: "en6_0598", de: "sehen", en: "see" },
  { id: "en6_0599", de: "denken", en: "think" },
  { id: "en6_0600", de: "ein paar", en: "a few" },
  { id: "en6_0601", de: "ohne", en: "without" },
  { id: "en6_0602", de: "antworten", en: "answer" },
  { id: "en6_0603", de: "wenn", en: "when" },
  { id: "en6_0604", de: "der Schulhof", en: "yard" },
  { id: "en6_0605", de: "warten", en: "wait" },
  { id: "en6_0606", de: "überrascht", en: "surprised" },
  { id: "en6_0607", de: "traurig", en: "sad" },
  { id: "en6_0608", de: "das Auge", en: "eye" },
  { id: "en6_0609", de: "sterben", en: "die" },
  { id: "en6_0610", de: "deshalb", en: "that's why" },
  { id: "en6_0611", de: "weinen", en: "cry" },
  { id: "en6_0612", de: "unfreundlich", en: "unfriendly" },
  { id: "en6_0613", de: "sammeln", en: "collect" },
  { id: "en6_0614", de: "das Gegenteil", en: "opposite" },
  { id: "en6_0615", de: "der Tipp", en: "tip" },
  { id: "en6_0616", de: "ungesund", en: "unhealthy" },
  { id: "en6_0617", de: "uninteressant", en: "uninteresting" },
  { id: "en6_0618", de: "unsicher", en: "unsure" },
  { id: "en6_0619", de: "unerwünscht", en: "unwelcome" },
  { id: "en6_0620", de: "seltsam", en: "strange" },
  { id: "en6_0621", de: "tragen (Kleidung)", en: "wear" },
  { id: "en6_0622", de: "der Schal", en: "scarf" },
  { id: "en6_0623", de: "oje!", en: "Oh dear!" },
  { id: "en6_0624", de: "wütend", en: "angry" },
  { id: "en6_0625", de: "schüchtern", en: "shy" },
  { id: "en6_0626", de: "der Nachbar", en: "neighbour", alt: ["neighbor"] },
  { id: "en6_0627", de: "das Postamt", en: "post office" },
  { id: "en6_0628", de: "die Werkstatt", en: "garage" },
  { id: "en6_0629", de: "die Elektronik", en: "electronics" },
  { id: "en6_0630", de: "die Gasse", en: "lane" },
  { id: "en6_0631", de: "der Kuchen", en: "cake" },
  { id: "en6_0632", de: "der Parkplatz", en: "car park", alt: ["carpark"] },
  { id: "en6_0633", de: "das Haar", en: "hair" },
  { id: "en6_0634", de: "der Zeitungshändler", en: "newsagent" },
  { id: "en6_0635", de: "der Briefkasten", en: "letter box", alt: ["letterbox"] },
  { id: "en6_0636", de: "der Friseur", en: "hairdresser" },
  { id: "en6_0637", de: "die Landkarte", en: "map" },
  { id: "en6_0638", de: "die Bushaltestelle", en: "bus stop" },
  { id: "en6_0639", de: "die Ampel", en: "traffic lights" },
  { id: "en6_0640", de: "die Blume", en: "flower" },
  { id: "en6_0641", de: "die Nachbarschaft", en: "neighbourhood", alt: ["neighborhood"] },
  { id: "en6_0642", de: "die Wurst", en: "sausage" },
  { id: "en6_0643", de: "beliebt", en: "popular" },
  { id: "en6_0644", de: "Großbritannien", en: "Great Britain" },
  { id: "en6_0645", de: "die Milch", en: "milk" },
  { id: "en6_0646", de: "das Brot", en: "bread" },
  { id: "en6_0647", de: "das Halsband", en: "collar" },
  { id: "en6_0648", de: "plötzlich", en: "suddenly" },
  { id: "en6_0649", de: "der Feuerwerkskörper", en: "firework" },
  { id: "en6_0650", de: "das Feuerwerk", en: "fireworks" },
  { id: "en6_0651", de: "rennen", en: "run" },
  { id: "en6_0652", de: "die Stunde", en: "hour" },
  { id: "en6_0653", de: "legen", en: "put" },
  { id: "en6_0654", de: "bringen", en: "bring" },
  { id: "en6_0655", de: "fallen", en: "fall" },
  { id: "en6_0656", de: "wissen", en: "know" },
  { id: "en6_0657", de: "klingeln", en: "ring" },
  { id: "en6_0658", de: "schicken", en: "send" },
  { id: "en6_0659", de: "der Besitzer", en: "owner" },
  { id: "en6_0660", de: "der Schwanz", en: "tail" },
  { id: "en6_0661", de: "erzählen", en: "tell" },
  { id: "en6_0662", de: "offen", en: "open" },
  { id: "en6_0663", de: "nehmen", en: "take" },
  { id: "en6_0664", de: "das Ohr", en: "ear" },
  { id: "en6_0665", de: "adoptieren", en: "adopt" },
  { id: "en6_0666", de: "ausgehen", en: "go out" },
  { id: "en6_0667", de: "prüfen", en: "check" },
  { id: "en6_0668", de: "spazieren gehen", en: "go for a walk" },
  { id: "en6_0669", de: "der Wellensittich", en: "budgie" },
  { id: "en6_0670", de: "das Freudenfeuer", en: "bonfire" },
  { id: "en6_0671", de: "feiern", en: "celebrate" },
  { id: "en6_0672", de: "das Kostüm", en: "costume" },
  { id: "en6_0673", de: "die Kartoffel", en: "potato" },
  { id: "en6_0674", de: "die Kleidung", en: "clothes" },
  { id: "en6_0675", de: "der Kakao", en: "cocoa" },
  { id: "en6_0676", de: "Neujahr", en: "New Year" },
  { id: "en6_0677", de: "die Hexe", en: "witch" },
  { id: "en6_0678", de: "das Geheimnis", en: "mystery" },
  { id: "en6_0679", de: "jemand", en: "someone", alt: ["somebody"] },
  { id: "en6_0680", de: "die Jacke", en: "jacket" },
  { id: "en6_0681", de: "die Maske", en: "mask" },
  { id: "en6_0682", de: "das Spielzeug", en: "toy" },
  { id: "en6_0683", de: "das Publikum", en: "audience" },
  { id: "en6_0684", de: "auswählen", en: "pick" },
  { id: "en6_0685", de: "der Schauspieler", en: "actor" },
  { id: "en6_0686", de: "deuten", en: "point" },
  { id: "en6_0687", de: "aufschauen", en: "look up" },
  { id: "en6_0688", de: "fast", en: "nearly" },
  { id: "en6_0689", de: "albern", en: "silly" },
  { id: "en6_0690", de: "flüstern", en: "whisper" },
  { id: "en6_0691", de: "der Brieffreund", en: "penfriend" },
  { id: "en6_0692", de: "mindestens", en: "at least" },
  { id: "en6_0693", de: "die Wegbeschreibung", en: "directions" },
  { id: "en6_0694", de: "überqueren", en: "cross" },
  { id: "en6_0695", de: "rechts abbiegen", en: "turn right" },
  { id: "en6_0696", de: "links abbiegen", en: "turn left" },
  { id: "en6_0697", de: "der Meter", en: "metre", alt: ["meter"] },
  { id: "en6_0698", de: "die Bank", en: "bank" },
  { id: "en6_0699", de: "das Toilettenpapier", en: "toilet roll" },
  { id: "en6_0700", de: "gruselig", en: "scary" },
  { id: "en6_0701", de: "erschrecken", en: "scare" },
  { id: "en6_0702", de: "perfekt", en: "perfect" },
  { id: "en6_0703", de: "relaxen", en: "chill" },
  { id: "en6_0704", de: "das Zeug", en: "stuff" },
  { id: "en6_0705", de: "Ski fahren", en: "ski" },
  { id: "en6_0706", de: "spannend", en: "exciting" },
  { id: "en6_0707", de: "die Umfrage", en: "survey" },
  { id: "en6_0708", de: "viel", en: "much" },
  { id: "en6_0709", de: "viele", en: "many" },
  { id: "en6_0710", de: "niemand", en: "nobody" },
  { id: "en6_0711", de: "die Zeitschrift", en: "magazine" },
  { id: "en6_0712", de: "die Tasche", en: "pocket" },
  { id: "en6_0713", de: "das Taschengeld", en: "pocket money" },
  { id: "en6_0714", de: "geizig", en: "mean" },
  { id: "en6_0715", de: "bis", en: "until" },
  { id: "en6_0716", de: "staubsaugen", en: "hoover" },
  { id: "en6_0717", de: "füllen", en: "fill" },
  { id: "en6_0718", de: "der Geschirrspüler", en: "dishwasher" },
  { id: "en6_0719", de: "leeren", en: "empty" },
  { id: "en6_0720", de: "schneiden", en: "cut" },
  { id: "en6_0721", de: "das Gras", en: "grass" },
  { id: "en6_0722", de: "den Rasen mähen", en: "cut the grass" },
  { id: "en6_0723", de: "aufräumen", en: "tidy" },
  { id: "en6_0724", de: "bitten (um)", en: "ask for" },
  { id: "en6_0725", de: "zum Beispiel", en: "for example" },
  { id: "en6_0726", de: "die Vereinbarung", en: "arrangement" },
  { id: "en6_0727", de: "der Plan", en: "plan" },
  { id: "en6_0728", de: "Schlittschuhlaufen", en: "ice skating" },
  { id: "en6_0729", de: "billig", en: "cheap" },
  { id: "en6_0730", de: "immer noch", en: "still" },
  { id: "en6_0731", de: "nächstes Mal", en: "next time" },
  { id: "en6_0732", de: "der Handschuh", en: "glove" },
  { id: "en6_0733", de: "die Brille", en: "glasses" },
  { id: "en6_0734", de: "der Wettkampf", en: "match" },
  { id: "en6_0735", de: "die Aktivität", en: "activity" },
  { id: "en6_0736", de: "der Erwachsene", en: "adult" },
  { id: "en6_0737", de: "kostenlos", en: "free" },
  { id: "en6_0738", de: "vorsichtig", en: "careful" },
  { id: "en6_0739", de: "Eishockey", en: "ice hockey" },
  { id: "en6_0740", de: "die Erde", en: "earth" },
  { id: "en6_0741", de: "der Zirkus", en: "circus" },
  { id: "en6_0742", de: "der Hai", en: "shark" },
  { id: "en6_0743", de: "der Angriff", en: "attack" },
  { id: "en6_0744", de: "wachsen", en: "grow" },
  { id: "en6_0745", de: "der Teil", en: "part" },
  { id: "en6_0746", de: "das Sofa", en: "sofa" },
  { id: "en6_0747", de: "der Müll", en: "rubbish" },
  { id: "en6_0748", de: "loswerden", en: "get rid of" },
  { id: "en6_0749", de: "wiederverwerten", en: "recycle" },
  { id: "en6_0750", de: "öffnen", en: "open (verb)", alt: ["open"] },
  { id: "en6_0751", de: "die Dartscheibe", en: "dartboard" },
  { id: "en6_0752", de: "sparen", en: "save" },
  { id: "en6_0753", de: "die Wand", en: "wall" },
  { id: "en6_0754", de: "bequem", en: "comfortable" },
  { id: "en6_0755", de: "der Pfeil", en: "dart" },
  { id: "en6_0756", de: "das Kleid", en: "dress" },
  { id: "en6_0757", de: "ankommen", en: "arrive" },
  { id: "en6_0758", de: "die Aufgabe", en: "task" },
  { id: "en6_0759", de: "der Vortrag", en: "talk" },
  { id: "en6_0760", de: "zeigen", en: "show" },
  { id: "en6_0761", de: "die Ausrüstung", en: "gear" },
  { id: "en6_0762", de: "entspannend", en: "relaxing" },
  { id: "en6_0763", de: "der Trainer", en: "coach" },
  { id: "en6_0764", de: "die Komödie", en: "comedy" },
  { id: "en6_0765", de: "die Krimiserie", en: "crime series" },
  { id: "en6_0766", de: "die Serie", en: "series" },
  { id: "en6_0767", de: "der Dokumentarfilm", en: "documentary" },
  { id: "en6_0768", de: "die Seife", en: "soap" },
  { id: "en6_0769", de: "die Realityshow", en: "reality show" },
  { id: "en6_0770", de: "die Wirklichkeit", en: "reality" },
  { id: "en6_0771", de: "am besten", en: "best" },
  { id: "en6_0772", de: "stimmen (für)", en: "vote" },
  { id: "en6_0773", de: "der Anführer", en: "leader" },
  { id: "en6_0774", de: "der Kartenschalter", en: "ticket office" },
  { id: "en6_0775", de: "weniger", en: "less" },
  { id: "en6_0776", de: "ungesundes Essen", en: "junk food" },
  { id: "en6_0777", de: "die Chips", en: "crisps" },
  { id: "en6_0778", de: "meistens", en: "mostly" },
  { id: "en6_0779", de: "zuckerhaltig", en: "sugary" },
  { id: "en6_0780", de: "der Zucker", en: "sugar" },
  { id: "en6_0781", de: "Zeit verbringen", en: "spend time" },
  { id: "en6_0782", de: "Geld ausgeben", en: "spend money" },
  { id: "en6_0783", de: "aktiv", en: "active" },
  { id: "en6_0784", de: "der Rat", en: "advice" },
  { id: "en6_0785", de: "zustimmen", en: "agree" },
  { id: "en6_0786", de: "die Hand", en: "hand" },
  { id: "en6_0787", de: "der Rücken", en: "back" },
  { id: "en6_0788", de: "der Arm", en: "arm" },
  { id: "en6_0789", de: "die Faust", en: "fist" },
  { id: "en6_0790", de: "das Knie", en: "knee" },
  { id: "en6_0791", de: "natürlich", en: "of course" },
  { id: "en6_0792", de: "die Ofenkartoffel", en: "baked potato" },
  { id: "en6_0793", de: "der Nachtisch", en: "dessert" },
  { id: "en6_0794", de: "die Pastete", en: "pasty" },
  { id: "en6_0795", de: "das Fleisch", en: "meat" },
  { id: "en6_0796", de: "vorher", en: "before" },
  { id: "en6_0797", de: "die Brotdose", en: "lunch box" },
  { id: "en6_0798", de: "die Karotte", en: "carrot" },
  { id: "en6_0799", de: "der Orangensaft", en: "orange juice" },
  { id: "en6_0800", de: "die Orange", en: "orange" },
  { id: "en6_0801", de: "die Salami", en: "salami" },
  { id: "en6_0802", de: "der Arzt", en: "doctor" },
  { id: "en6_0803", de: "dunkel", en: "dark" },
  { id: "en6_0804", de: "die Erdnussbutter", en: "peanut butter" },
  { id: "en6_0805", de: "die Frühstücksflocken", en: "cereals" },
  { id: "en6_0806", de: "der Smoothie", en: "smoothie" },
  { id: "en6_0807", de: "keiner", en: "none" },
  { id: "en6_0808", de: "genug", en: "enough" },
  { id: "en6_0809", de: "schwänzen", en: "skive" },
  { id: "en6_0810", de: "krank", en: "ill" },
  { id: "en6_0811", de: "Magenschmerzen", en: "stomach ache", alt: ["stomachache"] },
  { id: "en6_0812", de: "Kopfschmerzen", en: "headache" },
  { id: "en6_0813", de: "verlieren", en: "lose" },
  { id: "en6_0814", de: "umziehen", en: "move" },
  { id: "en6_0815", de: "Halsschmerzen", en: "a sore throat", alt: ["sore throat"] },
  { id: "en6_0816", de: "der Hals", en: "throat" },
  { id: "en6_0817", de: "die Erkältung", en: "cold" },
  { id: "en6_0818", de: "die Temperatur", en: "temperature" },
  { id: "en6_0819", de: "der Schlaf", en: "sleep" },
  { id: "en6_0820", de: "der Termin", en: "appointment" },
  { id: "en6_0821", de: "aufhören", en: "stop" },
  { id: "en6_0822", de: "frisch", en: "fresh" },
  { id: "en6_0823", de: "die Luft", en: "air" },
  { id: "en6_0824", de: "gerade", en: "just" },
  { id: "en6_0825", de: "verpassen", en: "miss" },
  { id: "en6_0826", de: "noch nicht", en: "not yet" },
  { id: "en6_0827", de: "schon", en: "already" },
  { id: "en6_0828", de: "durstig", en: "thirsty", alt: ["be thirsty"] },
  { id: "en6_0829", de: "sauer", en: "cross" },
  { id: "en6_0830", de: "alles", en: "everything" },
  { id: "en6_0831", de: "das Stadion", en: "stadium" },
  { id: "en6_0832", de: "enttäuscht", en: "disappointed" },
  { id: "en6_0833", de: "das Kätzchen", en: "kitten" },
  { id: "en6_0834", de: "der Anruf", en: "phone call" },
  { id: "en6_0835", de: "positiv", en: "positive" },
  { id: "en6_0836", de: "der Chat", en: "chat" },
  { id: "en6_0837", de: "ändern", en: "change" },
  { id: "en6_0838", de: "der Witz", en: "joke" },
  { id: "en6_0839", de: "lächeln", en: "smile" },
  { id: "en6_0840", de: "groß (Person)", en: "tall" },
  { id: "en6_0841", de: "klein (Person)", en: "short" },
  { id: "en6_0842", de: "sportlich", en: "sporty" },
  { id: "en6_0843", de: "schlau", en: "clever" },
  { id: "en6_0844", de: "der Typ", en: "guy" },
  { id: "en6_0845", de: "gelassen", en: "easy-going" },
  { id: "en6_0846", de: "besonders", en: "especially" },
  { id: "en6_0847", de: "vorziehen", en: "prefer" },
  { id: "en6_0848", de: "das Thema", en: "subject" },
  { id: "en6_0849", de: "die Nachricht", en: "message" },
  { id: "en6_0850", de: "sich freuen auf", en: "look forward to" },
  { id: "en6_0851", de: "klettern", en: "climb" },
  { id: "en6_0852", de: "Judo", en: "judo" },
  { id: "en6_0853", de: "die Gymnastik", en: "gymnastics" },
  { id: "en6_0854", de: "Bogenschießen", en: "archery" },
  { id: "en6_0855", de: "tauchen", en: "dive" },
  { id: "en6_0856", de: "genießen", en: "enjoy" },
  { id: "en6_0857", de: "verlegen", en: "embarrassed" },
  { id: "en6_0858", de: "der Schlamm", en: "mud" },
  { id: "en6_0859", de: "der Nationalpark", en: "national park" },
  { id: "en6_0860", de: "der Südwesten", en: "south-west" },
  { id: "en6_0861", de: "der Süden", en: "south" },
  { id: "en6_0862", de: "der Westen", en: "west" },
  { id: "en6_0863", de: "der Norden", en: "north" },
  { id: "en6_0864", de: "der Osten", en: "east" },
  { id: "en6_0865", de: "der Südosten", en: "south-east" },
  { id: "en6_0866", de: "der Nordosten", en: "north-east" },
  { id: "en6_0867", de: "der Nordwesten", en: "north-west" },
  { id: "en6_0868", de: "der Tourist", en: "tourist" },
  { id: "en6_0869", de: "der Fluss", en: "river" },
  { id: "en6_0870", de: "überall", en: "everywhere" },
  { id: "en6_0871", de: "beißen", en: "bite" },
  { id: "en6_0872", de: "sein", en: "be" },
  { id: "en6_0873", de: "der Fuchs", en: "fox" },
  { id: "en6_0874", de: "früher", en: "in the old days" },
  { id: "en6_0875", de: "riechen", en: "smell" },
  { id: "en6_0876", de: "die Wettervorhersage", en: "forecast" },
  { id: "en6_0877", de: "neblig", en: "foggy" },
  { id: "en6_0878", de: "der Nebel", en: "fog" },
  { id: "en6_0879", de: "der Stiefel", en: "boot" },
  { id: "en6_0880", de: "die Wanderstiefel", en: "walking boots" },
  { id: "en6_0881", de: "das Zelt", en: "tent" },
  { id: "en6_0882", de: "packen", en: "pack" },
  { id: "en6_0883", de: "der Schlafanzug", en: "pyjamas" },
  { id: "en6_0884", de: "der Föhn", en: "hairdryer" },
  { id: "en6_0885", de: "der Rucksack", en: "rucksack" },
  { id: "en6_0886", de: "die Jeans", en: "jeans" },
  { id: "en6_0887", de: "die Liste", en: "list" },
  { id: "en6_0888", de: "ob", en: "if" },
  { id: "en6_0889", de: "der Schritt", en: "step" },
  { id: "en6_0890", de: "vorwärts", en: "forward" },
  { id: "en6_0891", de: "geradeaus", en: "straight on" },
  { id: "en6_0892", de: "die Sicherheit", en: "safety" },
  { id: "en6_0893", de: "der Kompass", en: "compass" },
  { id: "en6_0894", de: "die Pfeife", en: "whistle" },
  { id: "en6_0895", de: "das Plastik", en: "plastic" },
  { id: "en6_0896", de: "der Erste-Hilfe-Kasten", en: "first aid kit" },
  { id: "en6_0897", de: "die Wolke", en: "cloud" },
  { id: "en6_0898", de: "wolkig", en: "cloudy" },
  { id: "en6_0899", de: "anziehen", en: "put on" },
  { id: "en6_0900", de: "zurücklassen", en: "leave" },
  { id: "en6_0901", de: "der Abfall", en: "litter" },
  { id: "en6_0902", de: "der Mülleimer", en: "litter bin" },
  { id: "en6_0903", de: "aufheben", en: "pick up" },
  { id: "en6_0904", de: "die Polizei", en: "police" },
  { id: "en6_0905", de: "die Zukunft", en: "future" },
  { id: "en6_0906", de: "der Zug", en: "train" },
  { id: "en6_0907", de: "verheiratet", en: "married" },
  { id: "en6_0908", de: "ledig", en: "single" },
  { id: "en6_0909", de: "die Jahreszeit", en: "season" },
  { id: "en6_0910", de: "der Frühling", en: "spring" },
  { id: "en6_0911", de: "der Herbst", en: "autumn" },
  { id: "en6_0912", de: "der Winter", en: "winter" },
  { id: "en6_0913", de: "der Grad", en: "degree" },
  { id: "en6_0914", de: "kühl", en: "cool" },
  { id: "en6_0915", de: "windig", en: "windy" },
  { id: "en6_0916", de: "der Wind", en: "wind" },
  { id: "en6_0917", de: "verschneit", en: "snowy" },
  { id: "en6_0918", de: "der Schnee", en: "snow" },
  { id: "en6_0919", de: "eiskalt", en: "freezing" },
  { id: "en6_0920", de: "minus", en: "minus" },
  { id: "en6_0921", de: "der Stein", en: "stone" },
  { id: "en6_0922", de: "die Brücke", en: "bridge" },
  { id: "en6_0923", de: "die Hütte", en: "cottage" },
  { id: "en6_0924", de: "das Kreuz", en: "cross (noun)", alt: ["cross"] },
  { id: "en6_0925", de: "der Kilometer", en: "kilometre", alt: ["kilometer"] },
  { id: "en6_0926", de: "fotografieren", en: "take photos" },
  { id: "en6_0927", de: "weit", en: "far" },
  { id: "en6_0928", de: "gelangen", en: "get to" },
  { id: "en6_0929", de: "der Boden", en: "ground" },
  { id: "en6_0930", de: "der Fels", en: "rock" },
  { id: "en6_0931", de: "rund", en: "round" },
  { id: "en6_0932", de: "schreien", en: "scream" },
  { id: "en6_0933", de: "rufen", en: "shout" },
  { id: "en6_0934", de: "die Stimme", en: "voice" },
  { id: "en6_0935", de: "der Bahnhof", en: "station" },
  { id: "en6_0936", de: "der Bahnsteig", en: "platform" },
  { id: "en6_0937", de: "der Fahrgast", en: "passenger" },
  { id: "en6_0938", de: "pünktlich", en: "on time" },
  { id: "en6_0939", de: "abfahren", en: "leave (train)" },
  { id: "en6_0940", de: "der Krankenwagen", en: "ambulance" },
  { id: "en6_0941", de: "der Notfall", en: "emergency" },
  { id: "en6_0942", de: "der Rettungsdienst", en: "emergency services" },
  { id: "en6_0943", de: "der Unfall", en: "accident" },
  { id: "en6_0944", de: "die Meile", en: "mile" },
  { id: "en6_0945", de: "verletzt", en: "hurt" },
  { id: "en6_0946", de: "verletzen", en: "injure", alt: ["hurt"] },
  { id: "en6_0947", de: "korrigieren", en: "correct" },
  { id: "en6_0948", de: "die Postkarte", en: "postcard" },
  { id: "en6_0949", de: "der Buchstabe", en: "letter" },
  { id: "en6_0950", de: "der Großbuchstabe", en: "capital letter" },
  { id: "en6_0951", de: "der Fehler", en: "mistake" },
  { id: "en6_0952", de: "die Sorte", en: "kind of", alt: ["kind"] },
  { id: "en6_0953", de: "der Stempel", en: "stamp" },
  { id: "en6_0954", de: "die Flagge", en: "flag" },
  { id: "en6_0955", de: "die Reise", en: "journey" },
  { id: "en6_0956", de: "der Pilger", en: "pilgrim" },
  { id: "en6_0957", de: "verlassen", en: "leave" },
  { id: "en6_0958", de: "das Schiff", en: "ship" },
  { id: "en6_0959", de: "segeln", en: "sail" },
  { id: "en6_0960", de: "berühmt", en: "famous" },
  { id: "en6_0961", de: "der Seemann", en: "sailor" },
  { id: "en6_0962", de: "kämpfen", en: "fight" },
  { id: "en6_0963", de: "gegen", en: "against" },
  { id: "en6_0964", de: "der Schmuggler", en: "smuggler" },
  { id: "en6_0965", de: "die Küste", en: "coast" },
  { id: "en6_0966", de: "der König", en: "king" },
  { id: "en6_0967", de: "die Legende", en: "legend" },
  { id: "en6_0968", de: "ziehen", en: "pull" },
  { id: "en6_0969", de: "das Schwert", en: "sword" },
  { id: "en6_0970", de: "werden", en: "become" },
  { id: "en6_0971", de: "der Zauberer", en: "magician" },
  { id: "en6_0972", de: "das Lager", en: "camp" },
  { id: "en6_0973", de: "die Fantasie", en: "fantasy" },
  { id: "en6_0974", de: "die Burg", en: "castle" },
  { id: "en6_0975", de: "die Treppe", en: "stairs" },
  { id: "en6_0976", de: "eintreten", en: "enter" },
  { id: "en6_0977", de: "der Gang", en: "hall" },
  { id: "en6_0978", de: "die Magie", en: "magic" },
  { id: "en6_0979", de: "erstaunlich", en: "amazing" },
  { id: "en6_0980", de: "bis jetzt", en: "so far" },
  { id: "en6_0981", de: "stehen", en: "stand" },
  { id: "en6_0982", de: "der Kapitän", en: "captain" },
  { id: "en6_0983", de: "die Fahrkarte", en: "ticket" },
  { id: "en6_0984", de: "die Kutsche", en: "carriage" },
  { id: "en6_0985", de: "das Pferd", en: "horse" },
  { id: "en6_0986", de: "einschalten", en: "switch on" },
  { id: "en6_0987", de: "ausschalten", en: "switch off" },
  { id: "en6_0988", de: "das Licht", en: "lights", alt: ["light"] },
  { id: "en6_0989", de: "die Information", en: "information" },
  { id: "en6_0990", de: "zerstören", en: "destroy" },
  { id: "en6_0991", de: "die Ruine", en: "ruins" },
  { id: "en6_0992", de: "die Höhle", en: "cave" },
  { id: "en6_0993", de: "bauen", en: "build" },
  { id: "en6_0994", de: "die Stufe", en: "step (stair)" },
  { id: "en6_0995", de: "bürsten", en: "brush" },
  { id: "en6_0996", de: "die Bürste", en: "brush (noun)" },
  { id: "en6_0997", de: "werfen", en: "throw" },
  { id: "en6_0998", de: "die Statue", en: "statue" },
  { id: "en6_0999", de: "winken", en: "wave" },
  { id: "en6_1000", de: "fantastisch", en: "fantastic" },
  { id: "en6_1001", de: "der Pfad", en: "track" },
  { id: "en6_1002", de: "nachschlagen", en: "look up a word" },
  { id: "en6_1003", de: "die Marionette", en: "puppet" },
  { id: "en6_1004", de: "die Insel", en: "island" },
  { id: "en6_1005", de: "ja", en: "yes" },
  { id: "en6_1006", de: "uncool", en: "uncool" }
];
